### ISSUE TITLE
'unexpected token' for EBNF lexer

### ISSUE THREAD

**Issue by the4thamigo-uk** [alecthomas/participle#101]
Hi, I think this library is great. However, I'm struggling with the EBNF lexer, which seems to be giving me `unexpected token` in many circumstances. Ive boiled the issue down to the example below (`Test1` succeeds but `Test2` fails with `unexpected token "example" (expected <ident2>)`). I suppose I'm doing something wrong?

```
package main

import (
	"github.com/alecthomas/participle"
	"github.com/alecthomas/participle/lexer"
	"github.com/alecthomas/participle/lexer/ebnf"
	"github.com/stretchr/testify/require"
	"testing"
)

func parse(s interface{}, cfg string) error {
	lex := lexer.Must(ebnf.New(`
		Ident = alpha { alpha } .
		Ident2 = alpha { alpha } .
		Whitespace = " " .
		alpha = "a"…"z" .
`))
	parser, err := participle.Build(s,
		participle.Lexer(lex),
		participle.Elide("Whitespace"),
	)
	if err != nil {
		return err
	}

	return parser.ParseString(cfg, s)
}

func Test1(t *testing.T) {
	type File struct {
		Package string `"package" @Ident`
	}

	err := parse(&File{}, `package example`)
	require.NoError(t, err)
}

func Test2(t *testing.T) {
	type File struct {
		Package string `"package" @Ident2`
	}

	err := parse(&File{}, `package example`)
	require.NoError(t, err)
}
```

**Comment by the4thamigo-uk** [comment]
Interestingly if I swap the order of the `Ident` and `Ident2` production rules, the tests reverse their plassing status. i.e.

```
	lex := lexer.Must(ebnf.New(`
		Ident2 = alpha { alpha } .
		Ident = alpha { alpha } .
		Whitespace = " " .
		alpha = "a"…"z" .
`))

**Comment by alecthomas** [comment]
Rules are checked in order.

**Comment by alecthomas** [comment]
Those two rules are identical, but they should not be.

**Comment by the4thamigo-uk** [comment]
Yes, they are the same because Ive simplified as much as possible, but if they are different, I still get the same problems :

```
	lex := lexer.Must(ebnf.New(`
		Ident = alphacase { alphacase } .
		Ident2 = alpha { alpha } .
		Whitespace = " " .
		alphacase = "a"…"z" | "A"…"Z" .
		alpha = "a"…"z" .
`))
```

**Comment by alecthomas** [comment]
I think there's a fundamental misunderstanding here. The way all these lexers work is that each rule is tested against the input in order. The first one that matches will be used. In your last example, because `Ident` captures lower *and* upper case, `Ident2` will never be considered.

**Comment by alecthomas** [comment]
Maybe if you describe exactly what you're trying to achieve, I can help.

**Comment by the4thamigo-uk** [comment]
Ok, thanks, for the pointer. I think I understand it now. Perhaps the only confusing thing is the error message, which would be clearer I think if it explained that the problem is a token type mismatch.

**Comment by alecthomas** [comment]
What's the error message?
