### ISSUE TITLE
« Anything but »

### ISSUE THREAD

**Issue by ceymard** [alecthomas/participle#104]
It would be useful to have an "Anything But" to match something that is anything but the specified rule.

```go
type Example struct {
  StuffUntilSemicolon *[]string ` ( @!";" )* ";"`
}
```

Or is there already a way to do that ?

(*edit*: forgot the `@`)

**Comment by ceymard** [comment]
I am aware that I could just create a special `SemiColon` token and match using `@(String | Float | .... all the other tokens)`, but it is cumbersome and it does not evolve well when adding / changing tokens to the lexer.

**Comment by alecthomas** [comment]
This seems like a pretty reasonable request.

**Comment by alecthomas** [comment]
This still wouldn't capture tokens elided by the lexer though.

**Comment by ceymard** [comment]
This is not a problem ; if I want elided token, then I use a lexer that doesn't elide. Grammar may suffer, but any ways, if it is about capturing *everything*, my other proposal should allow for that.

**Comment by ceymard** [comment]
Just two more cents ; `!` should be usable with `(` `)`, as in `@!(";" | ",")` would match anything but ";" or ","

**Comment by alecthomas** [comment]
That might be complicated as it would allow potentially unbounded lookahead, eg. in the case of `!("a" "b" "c")`. Though I could special case it to only allow a disjunction...

What does cover your example is defining a lexeme containing those two characters only, eg.

```
Terminal = [;,]
```

Then do the following in the AST:

```
Statement []string `@!Terminal*`
```

**Comment by ceymard** [comment]
How do I define such a Lexeme ? Custom Lexer ?

**Comment by ceymard** [comment]
Nevermind just got what you wanted to say...
