### ISSUE TITLE
Matching Tokens

### ISSUE THREAD

**Issue by ceymard** [alecthomas/participle#105]
In line with the « Anything But » that I suggested in #104, I am looking for a way to get the tokens around a match.
The idea would be that we could match a token without necessarily consume it.

```go
type Example struct {
  StartToken *lexer.Token `@?`
  SomeRuleThatMatches *[]string ` (@!";")+ ";" `
  EndToken *lexer.Token `@?`
}
```

Note that the `@?` is not a proposition, as I wonder what would make sense here.

Now as to why I would need it ; usually, the lexers ignore whitespace. This makes of course for a simpler and cleaner grammar, as there is no need to mention optional whitespace everywhere.

However, I sometimes need to access the "exact string" that was matched by a rule, discarded text included. This is because I'm writing parsers for incomplete languages where I do not care about the meaning of some constructs - I just want them "as is".

Is there already a way to do such things ? I tried to match `@Token` into a *lexer.Token, but that didn't work. Also, I think that it would be more useful for token extraction that they don't advance the parser.

**Comment by alecthomas** [comment]
This seems to be two proposals? One is to be able to determine what input range matched the entire rule. The other is to be able to somehow also included the any elided start/end tokens in this.

Participle will automatically fill in any field called `Tok lexer.Token` with the first token that matched (see [here](https://github.com/alecthomas/participle#error-reporting)). This is somewhat similar to what you're suggesting. I can see how a similar `EndTok lexer.Token` might also be automatically filled in. From this you could reconstruct the entire range of text. Seems useful.

What I'm less convinced by is the second part. Mostly because it would vastly complicate the parser+lexer , but also because I guess I don't understand why you'd want to do this?

**Comment by alecthomas** [comment]
Or maybe I'm misunderstanding and being able to capture the complete range would give you what you want? You would have to reconstruct the raw text from the position information in the token, but that's fairly trivial.

**Comment by ceymard** [comment]
Yes, I was planning to reconstruct.

If instead of "Tok" we can have any token field that gets the Peek'd token at that position, it would be *great*

**Comment by ceymard** [comment]
So instead, this proposition would become ; « any *lexer.Token field gets populated by the next token returned by Peek() at that position » or something.

**Comment by alecthomas** [comment]
Can you show me an example of what you're trying to achieve?

This would be quite a bit more complicated to implement than simply begin/end tokens, but if it's really useful maybe it's worthwhile.

**Comment by ceymard** [comment]
Start / End token would be enough for what I want.

What I want to achieve is simple and you already have guessed what it was ; reconstituting the original text that corresponds to a match, elided stuff along with it.

I'm writing a parser that parses SQL with some custom added syntax. However, I'm not trying to understand it *perfectly*, just enough to write logic *around it*. Which means I still have to keep the original code as is, because sometimes white space can be significant and I don't want to lose this information.

Mostly, it revolves around parsing the beginning of some statements and then get "the rest" up until a ";". This rest is kept because I will use it almost as-is, without having to try to parse the complexity of what could be inside (this is Postgres we're talking about, the grammar is fairly big)

**Comment by ceymard** [comment]
Another reason why Start / End is enough ; we can just write a specific rule for the portions where we want the matches to be kept.

Although having tokens everywhere we want would be "beautiful", it is not mandatory. The workaround is not a big burden on the programmer IMHO.

**Comment by ceymard** [comment]
Anyways, both #104 and this issue have one goal in common ; write "incomplete" grammars, where there are large swaths of the source code whose meaning is not important when parsing, but may be some other time.

**Comment by ceymard** [comment]
Holy molly you're fast.

**Comment by alecthomas** [comment]
Okay awesome, done.

Interestingly, I implemented a parser identical to the one you describe. It is used to identify which SQL statements should be run by gh-ost. To be honest it would have been useful to have something like you've described here and in the other issue. Here's the parser:

```go
var (
	sqlLexer = lexer.Must(lexer.Regexp(
		`(\s*--[^\n]*)` +
			`|(?P<WS>\s+)` +
			`|(?P<Ident>[a-zA-Z_][a-zA-Z0-9_]*|` + "`" + `[a-zA-Z_][a-zA-Z0-9_]*` + "`" + `)` +
			`|(?P<Number>[-+]?\d*\.?\d+([eE][-+]?\d+)?)` +
			`|(?P<String>'[^']*'|"(?:\\.|[^"])*")` +
			`|(?P<End>;)` +
			`|(?P<Punct>[[:punct:]])`,
	))
	whitespaceNormalise = regexp.MustCompile(`\s+`)
	wsToken             = sqlLexer.Symbols()["WS"]

	sqlParser = participle.MustBuild(
		&Query{},
		participle.Lexer(sqlLexer),
		participle.CaseInsensitive("Ident"),
		participle.UseLookahead(1),
	)
)

// Query AST.
type Query struct {
	AlterTable   *AlterTable   `  WS? "ALTER" WS ("TABLE" @@` // We need the table name for gh-ost.
	AlterVSchema *AlterVSchema `                  | "VSCHEMA" @@)`
	Other        string        `| WS? @("INSERT" | "UPDATE" | "CREATE" | "DROP") @WS { @WS | @Ident | @Punct | @String | @Number } End? WS?`
}

// AlterVSchema captures "ALTER VSCHEMA" statements.
type AlterVSchema struct {
	Alter string `WS { @WS | @Ident | @Punct | @String | @Number } End? WS?`
}
// AlterTable captures the table and alter clause from an "ALTER TABLE" statement.
type AlterTable struct {
	Table string `WS (@Ident ("." @Ident)* ) WS?`
	Alter string `{ @WS | @Ident | @Punct | @String | @Number } End? WS?`
}

```

**Comment by ceymard** [comment]
Yeah, `WS` everywhere :)

Actually, I've been toying with this idea for a while in https://github.com/ceymard/parseur but this was in javascript world.

I like your library because it's the only one I found in go land that allowed for precise typing without `.(casts)` everywhere.
