### ISSUE TITLE
Greater/Less than equal operators don't work

### ISSUE THREAD

**Issue by asicerik** [alecthomas/participle#110]
I was running into this when using my own code, then I went and tried it using the "uc" example.
Just change line 266:
while (i < n) {
to 
while (i <= n) {
and the code panics.
panic: 19:14: unexpected token "<" (expected ")")

**Comment by alecthomas** [comment]
This is just an ordering issue in the grammar. Longest match should be first.

**Comment by alecthomas** [comment]
This is also a more general dilemma in lexing/parsing - whether `<=` should be one lexeme or separated into two. So you can also solve this at the lexer level.

**Comment by mathnogueira** [comment]
I'm experiencing something like that as well and I'm out of ideas of how to solve it.

I have the following structs:

```go
type assertionParserObject struct {
	Attribute string       `( @Ident ( @"." @Ident )*)`
	Operator  string       `@( "contains" | "<=" | ">=" | "=" | "!=" | "<" | ">" )`
	Value     *parserValue `@@*`
}

type parserValue struct {
	String  *string  ` @String`
	Int     *int64   ` | @Int`
	Float   *float64 ` | @Float`
	Boolean *bool    ` | @("true" | "false")`
}
```

When I try to parse some string like: `variable = 200` or `variable < 350`, it works fine. However, when I try to parse `variable != 200`or `variable <= 300`, it fails.

`variable != 200` error:

```
unexpected token "!" (expected ("contains" | "<=" | ">=" | "=" | "!=" | "<" | ">")
```

`variable <= 300` error:

```
1:26: unexpected token "="
```

@alecthomas , I read your comment saying that longest match should be first, but even after changing it, the errors persists. Any idea of how I can fix them?
