### ISSUE TITLE
How to make a Recursive Grammar

### ISSUE THREAD

**Issue by colourdelete** [alecthomas/participle#115]
Hi. Go gives me this error when compiling a recursive grammar (ie a function call can contain a function call like: `print(abs(-10))`).
```
# command-line-arguments
parser.go:x:x: invalid recursive type Object
```
This probably happens because `Object` → `Block` → `Object` (`Block` is a code block). How do I make a recursive grammar like this one without errors from Go? Any help would be appreciated. Thank you.

**Comment by alecthomas** [comment]
You haven't provided _any_ code so I'm just going to guess that the field needs to be a pointer.

**Comment by colourdelete** [comment]
Thanks! The code works now. I just indeed not using pointers: 
```
Objects []Object `@@*`
```
