### ISSUE TITLE
"no match" error with stateful parser/lexer

### ISSUE THREAD

**Issue by colourdelete** [alecthomas/participle#119]
I am making a stateful parser/lexer using the stateful package. The grammar I defined does not match the intended one, since the program returns `1:2: no match`, which is not supposed to happen. 
I made a [minimum (ish) repo](https://gitlab.com/colourdelete/participle-min-repo) to reproduce the example (basically only the parser and some code to call the parse function). 
I am pretty sure this is my fault, since this is my first or second time using this stateful parser/lexer. Any help would be greatly appreciated.

`input.txt`
```
print('hello world')
```

`parser/ast.go`
```
package parser

type Obj struct {
	Prefix *Map     `@@?`
	Root   *ObjRoot `@@`
	Suffix []Map    `@@`
}

type ObjRoot struct {
	Block *Block `@@`
	Text  *Text  `|@@`
	Map   *Map   `|@@`
	Ref   *Ref   `|@@`
}

type RawBlock struct {
	Objs []Obj `@@`
}

type Block struct {
	OBrack string `@BlockOBrack`
	Objs   []Obj  `@@*`
	CBrack string `@BlockCBrack`
}

type Text struct {
	OSQuote string `@TextOSQuote`
	Text    string `@TextIn`
	CSQuote string `@TextCSQuote`
}

type Map struct {
	OParen   string    `@MapOParen`
	RawBlock *RawBlock `@@`
	CParen   string    `@MapCParen`
}

type Ref struct {
	Ident string `(@RefNonDot*@RefDot)+`
}
```

`parser/main.go`
```
package parser

import (
	"github.com/alecthomas/participle"
	"github.com/alecthomas/participle/lexer/stateful"
	"github.com/alecthomas/repr"
	"io"
	"log"
	"strings"
)

func Parse(src io.Reader) (*RawBlock, error) {
	def, err := stateful.New(stateful.Rules{
		"Root": {
			{`RawBlock`, `[^{]`, stateful.Push("RawBlock")},
		},
		"Block": {
			{"OBrack", `\[`, nil},
			{"CBrack", `\]`, stateful.Pop()},
		},
		"Obj": {
			stateful.Include("Root"),
			{`whitespace`, `\s+`, nil},
			{`Oper`, `[-+/*%]`, nil},
			{"Ident", `\w+`, nil},
			{"End", `}`, stateful.Pop()},
		},
		"Map": {
			{"OParen", `\(`, nil},
			{"CParen", `\)`, stateful.Pop()},
		},
		"Text": {
			{"OSQuote", `\(`, nil},
			{"In", `"(\\.|[^"\\])*"`, nil},
			{"CSQuote", `\)`, stateful.Pop()},
		},
		"Ref": {
			{"NonDot", `[^\.]`, nil},
			{"Dot", `\.`, nil},
		},
	})
	if err != nil {
		log.Fatal(err)
	}
	parser, err := participle.Build(&RawBlock{}, participle.Lexer(def))
	if err != nil {
		log.Fatal(err)
	}

	actual := &RawBlock{}
	buf := new(strings.Builder)
	_, err = io.Copy(buf, src)
	if err != nil {
		log.Fatal(err)
	}
	err = parser.ParseString(buf.String(), actual)
	if err != nil {
		log.Fatal(err)
	}
	repr.Println(actual)
	return nil, nil
}

```

**Comment by alecthomas** [comment]
The code in this issue doesn't work at all:

```
$ go run main.go
2020/11/26 14:24:37 Objs: Prefix: OParen: unknown token type "MapOParen"
exit status 1
```

I'm happy to help out, but you need to provide a copy/pasteable example that reproduces the issue.

**Comment by colourdelete** [comment]
Thanks for the quick reply. Sorry, I think I pasted the old version or something. I copied the files onto a repl.it here: https://repl.it/@kenshibata/ParticipleIssue119Example.

**Comment by alecthomas** [comment]
I see a couple of issues.

```
		"Root": {
			{`RawBlock`, `[^{]`, stateful.Push("RawBlock")},
		},
```

What's the goal here? This will a) consume a single character that is _not_ a `{` and then try to push to a new state that doesn't exist, `RawBlock`. This should really result in an error, so that's a bug in the stateful lexer.

Maybe jump in the Gophers Slack (link is in the README), issues aren't really a great forum for this kind of feedback.

**Comment by colourdelete** [comment]
Thanks, I think I misunderstood something in the documentation. I'll definitely ask this in the Slack.

**Comment by alecthomas** [comment]
BTW it doesn't really look like you need a stateful lexer here? Different states are only required when you're lexing entirely different sets of tokens, like an interpolated string inside an existing language, or HTML tags inside JS, for example.

**Comment by colourdelete** [comment]
I think I was confused. The regex lexer I was previously using was going to be deprecated, so I thought I'd try this out, but I now just realised that there is a ebnf lexer.

**Comment by alecthomas** [comment]
I would recommend using the stateful lexer - it's a superset of the regex lexer in that if you just put basically the same patterns as you had in your regex lexer into the `Root` state it should be almost identical.

**Comment by alecthomas** [comment]
Also because I've removed the EBNF lexer in the [v1 branch](https://github.com/alecthomas/participle/tree/v1) ;)
