### ISSUE TITLE
Bug in sql parser

### ISSUE THREAD

**Issue by scudette** [alecthomas/participle#12]
I was just playing with the examples and noticed that the sql parser is a little broken:

```
⟫ go run src/github.com/alecthomas/participle/_examples/sql/main.go "select * from foo where user = 1 + 2 + 3"
main: error: <source>:1:38: unexpected token "+"
exit status 1
```

**Comment by alecthomas** [comment]
Yes, it is not complete.

**Comment by scudette** [comment]
Can you please give some pointers on how to fix it?

**Comment by alecthomas** [comment]
Unfortunately it is very far from complete. It only supports rudimentary `SELECT` statements. That said if you look okay the source and the tutorial you should be able to extend it.

**Comment by scudette** [comment]
Thanks @alecthomas - I got it more or less working. It is quite a nice package coming from pyparsing participle is very similar and nice to work with :-).

**Comment by alecthomas** [comment]
Excellent, I'm glad you're enjoying it! If you improve the SQL parser I'd be interested in merging back in your changes if you're amenable.
