### ISSUE TITLE
Go get lexer path seems broken

### ISSUE THREAD

**Issue by sensedata1** [alecthomas/participle#120]
HI there, 

Our scenery install relies on participle and it's currently failing since pointing to /V2

```

package github.com/alecthomas/participle/v2/lexer: cannot find package "github.com/alecthomas/participle/v2/lexer" in any of:
--
66 | /root/.goenv/versions/1.13.8/src/github.com/alecthomas/participle/v2/lexer (from $GOROOT)
67 | /usr/local/src/github.com/alecthomas/participle/v2/lexer (from $GOPATH)

```
Thanks
Ben

**Comment by alecthomas** [comment]
I'm not sure what scenery is but both I can't this locally.

```
~/Development/foo $ go run foo.go
go: finding module for package github.com/alecthomas/participle/v2/lexer
go: found github.com/alecthomas/participle/v2/lexer in github.com/alecthomas/participle/v2 v2.0.0-alpha1
~/Development/foo $ cat foo.go 
package main

import "github.com/alecthomas/participle/v2/lexer"

var _ = lexer.Token{}

func main() {}
~/Development/foo $ cat bar.go 
package main

import "github.com/alecthomas/participle/lexer"

var _ = lexer.Token{}

func main() {}
~/Development/foo $ go run bar.go 
~/Development/foo $
```

Are you using Go modules? Participle will not work without Go modules.

**Comment by sensedata1** [comment]
Hi Alec, 
So it would appear that participle lexer is a dependency of scenery, which is a super useful tool for rendering terraform output into something nicely human readable. 

This is scenery: https://github.com/dmlittle/scenery

We have been installing scenery with go get in an aws codebuild container, which has been working very nicely until yesterday. I wasn't even aware of your project until then, nice project btw 👍 

I guess this is something broken with the way that scenery is handling go dependencies.
Interesting that you can't replicate locally. 
I will fork scenery and try to replicate the error I'm seeing in the codebuild container. Looks like this is not your problem, but I appreciate the reply. 

WIll update with more details following some more testing. 

Thanks
Ben

**Comment by alecthomas** [comment]
Ah ok I understand. The issue is indeed that they are not using Go modules.

**Comment by alecthomas** [comment]
Well, actually, that should still be fine as it looks like they're using a different dependency manager. The issue is that you should be using their [release binaries](https://github.com/dmlittle/scenery/releases) or their Go dependency manager, whichever works for you.

**Comment by alecthomas** [comment]
To clarify, they are using a older dependency manager like `dep`, which should still work. But `go get` on their repo would never have been reliable for you as you're basically pulling in random dependencies, it's just luck that it's worked up until this point.

**Comment by sensedata1** [comment]
Thanks Alec, much appreciated. We'll grab the binaries and use those going forward. 
Again, thanks for getting back so soon, and thanks for the crackin' work sir. 
Cheers
Ben
