### ISSUE TITLE
Question (bug?) Unexpected order of parsing terminals

### ISSUE THREAD

**Issue by ololosha228** [alecthomas/participle#124]
Here is the problem:

tldr, this example: https://play.golang.org/p/EbNQ4ky3vTr (don't look at govet warnings, lol) parsing boolean value as identificator, what i did wrong? bool terminal is prioritized in list of terminals, but `no` parsed as identificator. lol why

Note, go playground has build timeout and downloads packages too long, so run this code twice, it'll be guaranteed working

**Comment by alecthomas** [comment]
I can't look right now, but alternate options are tried in order, so ordering is important.

**Comment by ololosha228** [comment]
@alecthomas that is the question, cause if i'm not blind, docs doesn't cover this part

**Comment by ololosha228** [comment]
@alecthomas so, is this issue confirmed or i just did something wrong?

**Comment by alecthomas** [comment]
It looks like the docs need updating. I'm away for a week so I can't do this at the moment.

**Comment by ololosha228** [comment]
@alecthomas so what's this status? is it bug, or undocumented feature, or what?

**Comment by ololosha228** [comment]
@alecthomas i'm stupid, sorry, didn't see that you closed this issue with commit, my apologies)

Thanks a lot
