### ISSUE TITLE
Allow stateful.Push() without consuming any input

### ISSUE THREAD

**Issue by yapith-suplari** [alecthomas/participle#125]
Problem statement:
Today stateful.Push() fails if it doesn't consume any input. It seems limiting to classify this case as a bug.

Use case:
I want to parse: `<expr> as <alias>` like a SQL select, where `<expr>` is recursive and doesn't have precursor marker (and contains spaces)

By allowing ruleset switch without consuming any input, it allows the lexer to express "else" switch to the "Expr" ruleset.

Example lexer:
```
lexer.Must(stateful.New(stateful.Rules{
	"Root": {
		{"As", `(?i)\s+as\s+`, nil},
		{"Comma", ",", nil},
		{"Whitespace", `\s+`, nil},
		{"Wildcard", `\*`, nil},
		{"Expr", "", stateful.Push("Expr")},
	},
	"Expr": {
		{"String", `"`, stateful.Push("String")},
		{"Integer", `\d+`, nil},
		{"Func", `\w+\(`, stateful.Push("Func")},
		{"Ident", `\w+`, nil},
		stateful.Return(),
	},
	"Func": {
	},
	"String": {
	},
}))
```

Here's another idea that would also solve my issue, inspired by https://github.com/yhirose/go-peg. If a rule action can return a map[string]Token (currently just an err), I could perform sub-parsing in a rule action and its return value can be passed to the struct field assignment.

**Comment by alecthomas** [comment]
Can you give an example of the input you're trying to parse that causes this issue?

**Comment by yapith-suplari** [comment]
Oops, I didn't escape my example properly. Description updated. Thanks.

**Comment by alecthomas** [comment]
I still don't see an example of the input you're trying to parse?

But regardless, I think you are pushing too much responsibility into the lexer. Everything you've described should be done by the parser, not the lexer. The stateful lexer should only be used for situations where you absolutely _require_ distinct tokens.

**Comment by yapith-suplari** [comment]
Thanks for the education, I think I understand it better.
