### ISSUE TITLE
Boolean values not parsed correctly

### ISSUE THREAD

**Issue by saholman** [alecthomas/participle#129]
https://github.com/alecthomas/participle/blob/0251287814fbe3b94ec63f91cf372d3cedbf0cd8/nodes.go#L513

Shouldn't this be something like:

```
        case reflect.Bool:
            b, err := strconv.ParseBool(v.String())
            if err != nil {
                return nil, fmt.Errorf("invalid boolean %q: %s", v.String(), err)
            }
            v = reflect.ValueOf(b)
```

It seems like boolean values are being parsed as true if the value is "true" or "false". The documentation states "For integer and floating point types, a successful capture will be parsed with `strconv.ParseInt()` and `strconv.ParseBool()` respectively." but I'm not seeing ParseBool() called anywhere.

The best way to demonstrate this is with the SQL example here: https://github.com/alecthomas/participle/blob/master/_examples/sql/main.go#L148. Whether you put "true" or "false" Value.Boolean is always true.

**Comment by saholman** [comment]
My solution above isn't working for me. 

My main question is where is ParseBool being called? Or where _should_ it be called to correctly parse boolean values? 

If this isn't a bug, then how can I modify https://github.com/alecthomas/participle/blob/master/_examples/sql/main.go#L148 to correctly save the boolean value into Value.Boolean?

**Comment by alecthomas** [comment]
The documentation is erroneous, `strconv.ParseBool()` should be `strconv.ParseFloat()`. The previous line in the documentation is about bools and is correct:

> A successful capture match into a boolean field will set the field to true.

Re. the SQL example, that should not be correct because `Boolean` [implements Capture](https://github.com/alecthomas/participle/blob/master/_examples/sql/main.go#L16).

For more rationale behind why bool behaves as it does, see #114.

**Comment by alecthomas** [comment]
I'll update the documentation to clarify this.

**Comment by alecthomas** [comment]
The SQL example works, but is case sensitive (which it shouldn't be, but that's a separate issue):

```
$ go run ./sql 'SELECT * FROM a WHERE b = TRUE '                                                                                    master
&main.Select{
  Expression: &main.SelectExpression{
    All: true,
  },
  From: &main.From{
    TableExpressions: []*main.TableExpression{
      &main.TableExpression{
        Table: "a",
      },
    },
    Where: &main.Expression{
      Or: []*main.OrCondition{
        &main.OrCondition{
          And: []*main.Condition{
            &main.Condition{
              Operand: &main.ConditionOperand{
                Operand: &main.Operand{
                  Summand: []*main.Summand{
                    &main.Summand{
                      LHS: &main.Factor{
                        LHS: &main.Term{
                          SymbolRef: &main.SymbolRef{
                            Symbol: "b",
                          },
                        },
                      },
                    },
                  },
                },
                ConditionRHS: &main.ConditionRHS{
                  Compare: &main.Compare{
                    Operator: "=",
                    Operand: &main.Operand{
                      Summand: []*main.Summand{
                        &main.Summand{
                          LHS: &main.Factor{
                            LHS: &main.Term{
                              Value: &main.Value{
                                Boolean: &main.Boolean(true),
                              },
                            },
                          },
                        },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
  },
}
```

**Comment by saholman** [comment]
Ahh okay, Boolean implementing Capture is the part I was missing. Thanks for the quick response! This is an amazing tool.

**Comment by alecthomas** [comment]
Glad you're enjoying it!
