### ISSUE TITLE
Parsing quoted strings

### ISSUE THREAD

**Issue by alranel** [alecthomas/participle#130]
This is not an issue report, just sharing a bit of experience.
First off, thank you for such an useful, well designed and robust package. Implementing a parser with it is pure fun. 🙇 

I spent some time finding how to parse a string enclosed in single or double quotes, with escaped quotes inside like `"aa\"bb"` or `'aa\'bb'`. I had a look at the examples, but they use this rule which doesn't support escapes:

```go
{"String", `"[^"]*"`, nil},
```

The only solution I found was to implement it with a stateful parser like this:

```go
type Value struct {
	String   *string  `( "'" @(SingleQuotedStringChars | backslash | Char)* "'" | "\"" @(DoubleQuotedStringChars | backslash | Char)* "\"" )`
}

var mylexer = stateful.Must(stateful.Rules{
	"Root": {
		{`SingleQuotes`, `'`, stateful.Push("SingleQuotedString")},
		{`DoubleQuotes`, `"`, stateful.Push("DoubleQuotedString")},
	},
	"SingleQuotedString": {
		{"backslash", `\\`, stateful.Push("EscapedChar")},
		{"SingleQuotes", `'`, stateful.Pop()},
		{"SingleQuotedStringChars", `[^'\\]+`, nil},
	},
	"DoubleQuotedString": {
		{"backslash", `\\`, stateful.Push("EscapedChar")},
		{"DoubleQuotes", `"`, stateful.Pop()},
		{"DoubleQuotedStringChars", `[^"\\]+`, nil},
	},
	"EscapedChar": {
		{"Char", `.`, stateful.Pop()},
	},
})

var myparser = participle.MustBuild(&Tag{},
	participle.Lexer(mylexer),
)
```

It doesn't look too clean so I wonder if there are better ways to do this. If I understand correctly, the default lexer based on `text/scanner` would do this but if I need to define my own lexer rules it gets overridden.

Posting this in case it may be helpful for other people (or in case anyone can point me to a more clever implementation!). Feel free to close this non-issue :)

**Comment by alecthomas** [comment]
Glad you're finding it useful! There is a simpler solution: `"(\\"|[^"])*"`. This can also be extended with support for other escape sequences including octal values.

**Comment by alranel** [comment]
Ha! That is much simpler indeed. Thank you for sharing :)
