### ISSUE TITLE
Literal included in recursive capture

### ISSUE THREAD

**Issue by colinking** [alecthomas/participle#131]
Was building a variant of the GraphQL example and noticed that the example failed when you remove the `Punct` rule, which surprised me. Specifically, the `Punct` rule appeared to be used to capture the `{}`'s which should have already been captured by `Schema.Fields`, iiuc.

I created a smaller example to see why:

```go
// Runnable at: https://play.golang.org/p/9zsrEuARc7p
package main

import (
	"fmt"
	"strings"

	"github.com/alecthomas/participle/v2"
	"github.com/alecthomas/participle/v2/lexer/stateful"
	"github.com/alecthomas/repr"
)

type DSL struct {
	Fields []*Field `'{' @@* '}'`
}

type Field struct {
	Name string `@Ident`
}

func main() {
	dsl := &DSL{}
	lex, err := stateful.NewSimple([]stateful.Rule{
		{
			Name:    "Ident",
			Pattern: `[a-zA-Z]+`,
		},
		
		// *************************
		// Uncomment me and it works:
		// {"Punct", `[{}]`, nil},
        // *************************
		
		{
			Name:    "whitespace",
			Pattern: `[ \t\n\r]+`,
		},
	})
	if err != nil {
		panic(err)
	}

	parser, err := participle.Build(
		&DSL{},
		participle.Lexer(lex),
		participle.UseLookahead(2),
	)
	if err != nil {
		panic(err)
	}

	content := `{ foo }`
	fmt.Printf("parser:\n%s\n", parser.String())
	if err := parser.Parse("main", strings.NewReader(content), dsl); err != nil {
		panic(err)
	}

	repr.Println(dsl)
}

```

When run without the `Punct` rule:

```
panic: main:1:1: invalid input text "{ foo }"
```

But when run with it:

```
&main.DSL{
  Fields: []*main.Field{
    {
      Name: "foo",
    },
  },
}
```

My expectation is that participle would attempt to parse a `Field` from just ` foo }` not `{ foo }` since the leading curly bracket would have already been captured by `DSL.Fields`. Unless is this not how `@@*` would work here? FYI, this is with the latest v2.0.0-alpha3.

Thanks!

**Comment by alecthomas** [comment]
Any tokens used by the parser must be produced by the lexer.

**Comment by colinking** [comment]
Aha, I see where my confusion was. I had assumed that the lexer pulled out literals from the parser grammar and treated them as possible tokens. So this makes sense now. Thanks for the quick response!
