### ISSUE TITLE
Performance issue with disjunction error string generation

### ISSUE THREAD

**Issue by petee-d** [alecthomas/participle#143]
Hi, first of all, this struct-based approach to defining a grammar is very cool, great library!

I would like to report a performance issue I've noticed when using disjunctions, especially with common prefixes. It's something that will inherently make a recursive descent backtracking parser slower, but it's being made much slower than it should be because of slow generating of error strings that will never be used. Consider this stupid example constructed just to show the issue:

```golang
type Disjunctions struct {
	List []Disjunction `parser:"@@*"`
}

type Disjunction struct {
	Long1 bool `parser:"  '<' '1' ' ' 'l' 'o' 'n' 'g' ' ' 'r' 'u' 'l' 'e' ' ' 't' 'o' ' ' 'f' 'o' 'r' 'm' 'a' 't' '>'"`
	Long2 bool `parser:"| '<' '2' ' ' 'l' 'o' 'n' 'g' ' ' 'r' 'u' 'l' 'e' ' ' 't' 'o' ' ' 'f' 'o' 'r' 'm' 'a' 't' '>'"`
	Long3 bool `parser:"| '<' '3' ' ' 'l' 'o' 'n' 'g' ' ' 'r' 'u' 'l' 'e' ' ' 't' 'o' ' ' 'f' 'o' 'r' 'm' 'a' 't' '>'"`
	Long4 bool `parser:"| '<' '4' ' ' 'l' 'o' 'n' 'g' ' ' 'r' 'u' 'l' 'e' ' ' 't' 'o' ' ' 'f' 'o' 'r' 'm' 'a' 't' '>'"`
	Real  bool `parser:"| '<' 'x' '>'"`
}

var disjunctionParser = participle.MustBuild(&Disjunctions{})

func BenchmarkParticipleAlternative(b *testing.B) {
	input := "<x> <x> <x> <x> <x> <x> <x> <x> <x> <x> <x> <x> <x> <x> <x> <x> <x> <x> <x> <x>"
	ast := &Disjunctions{}
	for i := 0; i < b.N; i++ {
		if err := disjunctionParser.ParseString("", input, ast); err != nil {
			panic(err)
		}
	}
}
```

Takes ~600 microseconds per parsing, here is the CPU profile:
![image](https://user-images.githubusercontent.com/7727916/116861297-2de82500-ac03-11eb-8c2a-0a08adf510c0.png)

As you can see, the vast majority of the time is spent constructing the EBNF for the error message in `(*sequence).Parse`. This error message however wouldn't ever be used by `(*disjunction).Parse` as it just tries the next alternative and ultimately throws the error away. And generating that error is very costly, not just because of the string concatenation but also because of the string formatting and allocations.

The grammar can be relatively easily fixed by extracting the common prefix outside the alternatives (reduces parsing time to about 60 microseconds) but it might also be a good idea to somehow delay the generation of the error message until we know it's actually needed, as for many grammars such an optimization would significantly reduce readability or affect the parse tree structure. When I modify the `ebnf` function to just return an empty string, the parsing time drops to below 100 microseconds. To fix it, you could for example change `UnexpectedTokenError.Expected` to `fmt.Stringer` and materialize the string representation only when needed. Another improvement could be detecting common prefixes in alternatives and optimizing those automagically, but that's of course a different scale of a change.

**Comment by alecthomas** [comment]
Interesting, have you noticed this in practice?

**Comment by petee-d** [comment]
Yes, I noticed it when writing a parse for [Jinja](https://jinja.palletsprojects.com/en/2.11.x/), where I had the opening tag token `{%` in each rule for the various types of tags for example, also some other rules where extracting the common prefix would make the parse tree ugly. Making `ebnf` return an empty string early gets me a 4x improvement in performance on even the simplest templates.

**Comment by alecthomas** [comment]
Aah I see. Unfortunate, let me take a look.

**Comment by alecthomas** [comment]
Okay give that a go - it's on the v2 branch.

**Comment by alecthomas** [comment]
Before and after:

```
BenchmarkParticipleAlternative-12    	   2557	   435851 ns/op	 267897 B/op	   7893 allocs/op
BenchmarkParticipleAlternative-12    	  18913	    62182 ns/op	  60520 B/op	    933 allocs/op
```

**Comment by alecthomas** [comment]
Nice find BTW, thanks!

**Comment by petee-d** [comment]
Wow, that was a fast fix, amazing! :+1: Performance improved as anticipated, test suite still passes, many thanks!
