### ISSUE TITLE
Antlr4

### ISSUE THREAD

**Issue by tooolbox** [alecthomas/participle#156]
There are a lot of grammars available for Antlr4, I think something like 200 in [this repo](https://github.com/antlr/grammars-v4) alone.  However the experience of using it with Go is pretty terrible.

So, I used Participle to write a parser for Antlr v4 grammars:

```go
package antlr4

import (
	"github.com/alecthomas/participle/v2"
	"github.com/alecthomas/participle/v2/lexer/stateful"
)

var (
	Lexer = stateful.Must(stateful.Rules{
		"Root": {
			{"comment", `//[^\n]*`, nil},
			{"comment2", `/\\*`, stateful.Push("BlockComment")},
			{"String", `'(\\\\|\\'|[^'])*'`, nil},
			{"Group", `\[(\\]|[^\]])*\]`, nil},
			{"UpperIdent", `[A-Z][a-zA-Z_]*\w*`, nil},
			{"LowerIdent", `[a-z][a-zA-Z_]*\w*`, nil},
			{"Punct", `[-[!@#$%^&*()+_={}\|:;"'<,>.?/~]|]`, nil},
			{"whitespace", `[ \t\r\n]+`, nil},
		},
		"BlockComment": {
			{"end", "\\*/", stateful.Pop()},
			{"any", "([^*]|\\*[^/])+", nil},
		},
	})
	Parser = participle.MustBuild(&AntlrFile{},
		participle.Lexer(Lexer),
		participle.UseLookahead(2),
	)
)

type AntlrFile struct {
	Grammar *GrammarStmt `parser:" @@ "`
	Options *OptionStmt  `parser:" @@? "`
	Rules   []*Rule      `parser:" @@* "`
}

type GrammarStmt struct {
	LexerOnly  bool   `parser:" @'lexer'? "`
	ParserOnly bool   `parser:" @'parser'? "`
	Name       string `parser:" 'grammar' @( UpperIdent | LowerIdent) ';' "`
}

type OptionStmt struct {
	Opts []*Option `parser:" 'options' '{' @@ '}' "`
}

type Option struct {
	Key   string `parser:" @(LowerIdent|UpperIdent) '=' "`
	Value string `parser:" @(LowerIdent|UpperIdent) ';' "`
}

type Rule struct {
	LexRule *LexerRule  `parser:" ( @@ "`
	PrsRule *ParserRule `parser:" | @@ ) "`
}

type ParserRule struct {
	Name string       `parser:" @LowerIdent ':' "`
	Alt  *Alternative `parser:" @@ ';' "`
}

type LexerRule struct {
	Fragment bool         `parser:" @'fragment'? "`
	Name     string       `parser:" @UpperIdent ':' "`
	Alt      *Alternative `parser:" @@ "`
	Skip     bool         `parser:" ('-' '>' ( @'skip' "`
	Channel  string       `parser:" | 'channel' '(' @UpperIdent ')' ) )? ';' "`
}

type Alternative struct {
	Exp   *Expression  `parser:" @@? "`
	Label *string      `parser:" ('#' @UpperIdent)? "`
	Next  *Alternative `parser:" ( '|' @@ )? "`
}

type Expression struct {
	Label   *string     `parser:" ( @(UpperIdent|LowerIdent) "`
	LabelOp *string     `parser:" @( '=' | '+' '=' ) )? "`
	Unary   *Unary      `parser:" @@ "`
	Next    *Expression `parser:" ( @@ )? "`
}

type Unary struct {
	Op      string   `parser:" ( @( '~' ) "`
	Unary   *Unary   `parser:"     @@   ) "`
	Primary *Primary `parser:" | @@ "`
}

type Primary struct {
	Range     *CharRange   `parser:" ( @@ "`
	Str       *string      `parser:" | @String "`
	Ident     *string      `parser:" | @(UpperIdent|LowerIdent) "`
	Group     *string      `parser:" | @Group "`
	Any       bool         `parser:" | @'.' "`
	Sub       *Alternative `parser:" | '(' @@ ')' ) "`
	Arity     string       `parser:" ( @('+' | '*' | '?') "`
	NonGreedy bool         `parser:"   @'?'? )? "`
}

type CharRange struct {
	Start string `parser:" @String '.' '.' "`
	End   string `parser:" @String "`
}
```

Before I set up a PR, I'm wondering if this is something you would be interested in having this in the `examples` folder.

Further, I have also made some progress on generating a Participle parser based on the above AST.  I'm wondering if you think something like that would have a home here.

**Comment by alecthomas** [comment]
Definitely!

I'm not sure what you mean, how is"generating a parser" different to what you have now?

**Comment by alecthomas** [comment]
Oh do you mean generating a Participle parser from an ANTLR .g4 file via this parser?

Great question and coincidentally I had just started doing something very similar to this, though my AST isn't anywhere near as complete as yours:

```
	cmd/antlr2participle/Lua.g4
	cmd/antlr2participle/go.mod
	cmd/antlr2participle/go.sum
	cmd/antlr2participle/main.go
```

I think the idea of generating a Participle parser from an ANTLR grammar is great. However, the path I'd prefer it to take would be to translate it to Participle's EBNF form, then write a an ebnf2participle code generator that takes that EBNF and outputs a Participle grammar. This would result in Participle's EBNF being the lingua franca and close #14. Would you be interested in doing this?

The parser for Participle's EBNF already exists in participle/ebnf.


```
	cmd/ebnf2participle/ebnf.ebnf
	cmd/ebnf2participle/go.mod
	cmd/ebnf2participle/go.sum
	cmd/ebnf2participle/main.go
```

**Comment by alecthomas** [comment]
What I'd like to end up with is something like this:

```
$ cat Lua.g4 | antlr2participle | participle > lua.go
```

**Comment by tooolbox** [comment]
> Oh do you mean generating a Participle parser from an ANTLR .g4 file via this parser?

Yeah, exactly 😄 

> Great question and coincidentally I had just started doing something very similar to this, though my AST isn't anywhere near as complete as yours:

Neat!  (Are those files available anywhere, or just on your local?  Didn't see them in the repo.)

> I think the idea of generating a Participle parser from an ANTLR grammar is great. However, the path I'd prefer it to take would be to translate it to Participle's EBNF form, then write a an ebnf2participle code generator that takes that EBNF and outputs a Participle grammar. This would result in Participle's EBNF being the lingua franca and close #14. Would you be interested in doing this?

I do see the potential advantage to going via EBNF, however I have mixed feelings on this.

I suppose my basic concern is that I'm not familiar with EBNF.  I've spent the past few days studying ANTLR syntax, but I have no idea if it can cleanly map to EBNF.  I would need to read up on it I suppose.

For the sake of discussion, let's take an example, the GraphQL EBNF you have in the readme:

```ebnf
File = Entry* .
Entry = Type | Schema | Enum | "scalar" ident .
Type = "type" ident ("implements" ident)? "{" Field* "}" .
Field = ident ("(" (Argument ("," Argument)*)? ")")? ":" TypeRef ("@" ident)? .
Argument = ident ":" TypeRef ("=" Value)? .
TypeRef = "[" TypeRef "]" | ident "!"? .
Value = ident .
Schema = "schema" "{" Field* "}" .
Enum = "enum" ident "{" ident* "}" .
```

What is this in ANTLR?

```antlr
file: entry* ;
entry: type | schema | enum | 'scalar' IDENT ;
type: 'type' IDENT ('implements' IDENT)? '{' field* '}' ;
field: IDENT ('(' (argument (',' argument)*)? ')')? ':' type_ref ('@' IDENT)? ;
argument: IDENT ':' type_ref ('=' value)? ;
type_ref: '[' type_ref ']' | IDENT '!'? ;
value: IDENT ;
schema: 'schema' '{' field* '}' ;
enum: 'enum' IDENT '{' IDENT* '}' ;
```

That seems pretty clean, and is legal in a `.g4` file.  However Antlr also describes the lexer in the same or a related file (or implies lexer behavior via string literals in parser rules).  I think a canonical example is the JSON syntax:

```antlr
/** Taken from "The Definitive ANTLR 4 Reference" by Terence Parr */

// Derived from http://json.org
grammar JSON;

json
   : value
   ;

obj
   : '{' pair (',' pair)* '}'
   | '{' '}'
   ;

pair
   : STRING ':' value
   ;

arr
   : '[' value (',' value)* ']'
   | '[' ']'
   ;

value
   : STRING
   | NUMBER
   | obj
   | arr
   | 'true'
   | 'false'
   | 'null'
   ;


STRING
   : '"' (ESC | SAFECODEPOINT)* '"'
   ;


fragment ESC
   : '\\' (["\\/bfnrt] | UNICODE)
   ;
fragment UNICODE
   : 'u' HEX HEX HEX HEX
   ;
fragment HEX
   : [0-9a-fA-F]
   ;
fragment SAFECODEPOINT
   : ~ ["\\\u0000-\u001F]
   ;


NUMBER
   : '-'? INT ('.' [0-9] +)? EXP?
   ;


fragment INT
   : '0' | [1-9] [0-9]*
   ;

// no leading zeros

fragment EXP
   : [Ee] [+\-]? INT
   ;

// \- since - means "range" inside [...]

WS
   : [ \t\n\r] + -> skip
   ;
```

Would it be possible to translate that to EBNF, and then to Participle?  Does EBNF differentiate between lexer and parser tokens?  Can it specify that a particular lexer token is discarded?  Recursive tokens?  (Not that I have figured out supporting that yet, will likely need to write a custom lexer.)  Any other sharp edges you can think of?

In the meantime, I've made some progress on the direct Antlr -> Participle, for example my generator outputs a working lexer for JSON based on the above grammar.  The parse objects are a bit trickier to get right.

**Comment by alecthomas** [comment]
Good point re. lexers. I punted on that by just ignoring the lexer part, but for a generalised solution that would not suffice.

The current EBNF has no concept of lexing, so it would definitely need to be extended. How does Antlr describe sub-lexers?

I think rather than blocking you on that, go ahead and do the antlr2participle. In the meantime I'll extend the EBNF format so that once your code is merged I can adapt it to the new EBNF format.
