### ISSUE TITLE
Negation breaks own EBNF parsing

### ISSUE THREAD

**Issue by asmaloney** [alecthomas/participle#158]
When using `!<expr>` (as implemented in [this commit](https://github.com/alecthomas/participle/pull/106/commits/d97c4b630ee96b575881f465c67c88b4f43ab49d)), the EBNF that is produced cannot be read by the included EBNF parser, which breaks the `railroad` tool.

Example:
```go
type Item struct {
	Text string `parser:"(@!CloseBrace)+"`
}
```

produces this in the EBNF:
```
Item = !<closebrace>+ .
```

When running `railroad` on it, we get the error: `panic: /dev/stdin:14:10: sub-expression Term+ must match at least once`

My knowledge of BNF/EBNF is almost lost to the mists of time, but when I looked into it, there doesn't seem to be a way to indicate negation in standard EBNF, so I'm not sure what a good solution is.

(I also notice that the terms output by `parse.String()` are terminated with '.' instead of ';' which seems to be what [EBNF syntax](https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form) requires - was that intentional?)

**Comment by asmaloney** [comment]
One (perhaps hacky) way to fix this would be to change the `parser.String()` output to do this:
```
Item = <not_closebrace>+ .
```

**Comment by alecthomas** [comment]
Coincidentally I noticed this myself recently and have a fix coming soon :)

**Comment by alecthomas** [comment]
Turns out I had the commit (5c4f5190a26bb2e0f17c978e6ebe6004e9be7b36) locally but hadn't pushed it. Give latest master a whirl.

**Comment by alecthomas** [comment]
(BTW as that commit mentions I changed it from `!` to `~` due to an ambiguity in parsing which could result in very odd behaviour. I would recommend switching.)

**Comment by asmaloney** [comment]
Thanks @alecthomas.

`railroad` still panics though (in a different pace):

```
panic: ??

main.countProductions(0xc000145e78, 0x10ec180, 0xc000010950, 0xb)
	participle/cmd/railroad/main.go:148 +0x57e
main.countProductions(0xc000145e78, 0x10ec1e0, 0xc000154280, 0x1)
	participle/cmd/railroad/main.go:143 +0x51f
main.countProductions(0xc000145e78, 0x10ec120, 0xc00000d0c8, 0x1012102)
	participle/cmd/railroad/main.go:136 +0x198
main.countProductions(0xc000145e78, 0x10ec060, 0xc00000df50, 0x4)
	participle/cmd/railroad/main.go:132 +0xd8
main.countProductions(0xc000145e78, 0x10e3680, 0xc00000d038, 0x0)
	participle/cmd/railroad/main.go:129 +0x457
main.countProductions(0xc000145e78, 0x10ec000, 0xc00000c768, 0x112e9a8)
	participle/cmd/railroad/main.go:121 +0x30a
main.main()
	participle/cmd/railroad/main.go:161 +0x219
....
```

**Comment by asmaloney** [comment]
(It seems unrelated to this negation stuff - I'll open another issue.)
