### ISSUE TITLE
{railroad} Fails on SubExpressions

### ISSUE THREAD

**Issue by asmaloney** [alecthomas/participle#161]
The switch statements in `railroad` don't handle `*ebnf.SubExpression`, so will panic if they are used.

**Comment by alecthomas** [comment]
I can fix this panic obviously, but unfortunately I don't think there's a way to express negation via railroad diagrams, as they are a non-standard extension to EBNF. The same is true for lookahead assertions.

So I'm not sure what to do about that. I'll probably just print a warning and ignore them.

**Comment by asmaloney** [comment]
Yeah - I didn't find a way either.

Maybe since there's more control when generating the diagrams we can insert the string "not " in front of the identifier or string text? It might not be "standard" but it would be quite readable.

<img width="302" alt="Screen Shot 2021-07-20 at 20 53 53 PM" src="https://user-images.githubusercontent.com/391371/126413521-51a1c9d7-3b4f-43fc-9631-278f74c98817.png">

**Comment by alecthomas** [comment]
That's a good idea!

I'll do the same for the assertions.

**Comment by asmaloney** [comment]
(BTW - these diagrams are awesome. Great for debugging and great for communicating!)

**Comment by asmaloney** [comment]
This issue does not seem to be fixed.

`countProductions` still doesn't handle `*ebnf.SubExpression` in its switch.

Running with (7243a295a860f7c6d65ea9d7a74de53904d9524f):

```
panic: &ebnf.SubExpression{Expr: &ebnf.Expression{Alternatives: []*ebnf.Sequence{&ebnf.Sequence{Terms: []*ebnf.Term{&ebnf.Term{Token: "string", }}}, &ebnf.Sequence{Terms: []*ebnf.Term{&ebnf.Term{Token: "ident", }}}}}}

goroutine 1 [running]:
main.countProductions(0xc000187e78, 0x1195d88, 0xc000096c30, 0xb)
	participle/cmd/railroad/main.go:162 +0x5ea
main.countProductions(0xc000187e78, 0x1195da8, 0xc00019a2d0, 0x1)
	participle/cmd/railroad/main.go:157 +0x525
main.countProductions(0xc000187e78, 0x1195d68, 0xc0000a7110, 0x8)
	participle/cmd/railroad/main.go:150 +0x19b
main.countProductions(0xc000187e78, 0x1195d28, 0xc0000a7f98, 0x4)
	participle/cmd/railroad/main.go:146 +0xdb
main.countProductions(0xc000187e78, 0x1195d48, 0xc0000a7080, 0x0)
	participle/cmd/railroad/main.go:143 +0x457
main.countProductions(0xc000187e78, 0x1195d08, 0xc0000a67b0, 0x1195ea8)
	participle/cmd/railroad/main.go:135 +0x311
main.main()
	cmd/railroad/main.go:175 +0x219
```

**Comment by alecthomas** [comment]
PRs are welcome...

**Comment by asmaloney** [comment]
Alec: In case it came across as demanding, that was not my intent. Just pointing out that this issue should be reopened as it isn't fixed yet...

**Comment by alecthomas** [comment]
Aha! Good point :)
