### ISSUE TITLE
Support Matching EOF

### ISSUE THREAD

**Issue by tooolbox** [alecthomas/participle#165]
The parser actually supports matching `EOF` but then panics: `panic: m:2:41: branch <eof> was accepted but did not progress the lexer at m:2:41 ("") [recovered]`

I think it would be beneficial to special-case this check to allow matching the end of a file.

**Comment by alecthomas** [comment]
I've never had a case where this is necessary and I've never seen it used in other parsers - the grammar should terminate at an EOF naturally. Do you have an example of where this is required?

**Comment by tooolbox** [comment]
The [ANTLR CSV grammar](https://github.com/antlr/grammars-v4/blob/master/csv/CSV.g4#L34) requires a `\n` after ever row.  However real-world CSV files may end without a newline.  I could make the `\n` itself optional, but I believe it's more precise to say that a row ends with `('\n'|EOF)` in the grammar.

**Comment by alecthomas** [comment]
Seems reasonable.

**Comment by tooolbox** [comment]
Awesome!

Hm, I tried this out on my generated CSV grammar, changing the rule from `\n?` to `(\n|EOF)`.  It gave this error while parsing a two-row file:

```
--- FAIL: TestExe (2.21s)
    --- FAIL: TestExe/testdata/comma_in_quotes.csv (2.21s)
panic: m:2:41: too many iterations of Row+ (> 1000000) [recovered]
	panic: m:2:41: too many iterations of Row+ (> 1000000)
```

**Comment by alecthomas** [comment]
Well, that's accurate. Your grammar can now match nothing as every component is optional:

```
	Field []*Field `@@? ( ',' @@? )* '\r'? '\n'?`
```

**Comment by alecthomas** [comment]
What did you change it to exactly?

**Comment by tooolbox** [comment]
[There's](https://github.com/alecthomas/participle/pull/164/checks?check_run_id=3177542419) the failing test report, [there's](https://github.com/tooolbox/participle/blob/e0f8c5581a482361be74119ba2b8c9f60d0bbf88/_examples/csv/CSV.g4#L34) the exact syntax used.

The idea being that every row ends with either a newline, or the end of the file.

This
```
Field []*Field `@@? ( ',' @@? )* '\r'? '\n'?
``` 
works fine, reports no errors, since it just consumes all the tokens and then EOF's and quits.

**Comment by alecthomas** [comment]
The problem is that EOF is returned for any reads past the end of the stream. In your case you're repeatedly, successfully consuming an EOF, so the rule does successfully match, but never ends.

**Comment by alecthomas** [comment]
I'm not sure what the heuristics should be. Perhaps once an EOF is explicitly matched at any point, parsing should abort.

**Comment by tooolbox** [comment]
> I'm not sure what the heuristics should be. Perhaps once an EOF is explicitly matched at any point, parsing should abort.

That sounds exactly right.

**Comment by alecthomas** [comment]
I'm not sure it is exactly, but maybe it will just have to be a gotcha.

eg. if you use EOF at multiple levels of the grammar it will not succeed.

```go
type Outer struct {
  Inner []*Inner `@@* EOF`
}

type Inner struct {
  Words []string `@Ident* ("\n"|EOF)`
}
```

But maybe that's just the limitation.

**Comment by tooolbox** [comment]
> eg. if you use EOF at multiple levels of the grammar it will not succeed.

Meaning it will be semantically unsound, or will actually error?

I imagine a good rule of thumb is that if you need to use EOF, you should be using it only on one struct.  I haven't seen a grammar that needed it on more than one.

**Comment by alecthomas** [comment]
> Meaning it will be semantically unsound, or will actually error?

It would error because the outer branch did not succeed.

**Comment by tooolbox** [comment]
Interesting.  Well, two points:

1. The ~1 time I saw it in an ANTLR grammar, it was in the top-level rule.  I'm guessing that's how most uses will be.
2. What I would imagine for the CSV example is that it can match that last row, but stops trying to get more rows.

Perhaps EOF can match at most once in a given parse run or something.

(If this is too much hassle, I can just revert the CSV grammar, it works fine with an optional `\n`)
