### ISSUE TITLE
UUID matching

### ISSUE THREAD

**Issue by leaanthony** [alecthomas/participle#166]
Hey Alec! Awesome project and easily the best parser library I've used. Just wandering the best way to parse a UUID? The default lexer is perfect for my use case, apart from this one thing. Is it possible to extend the default lexer or would I need to recreate the default lexer and add my specific rule? Cheers!
EDIT: I've tried consuming all tokens in a greedy fashion and this worked great until an 'e' was present, then I got a "exponent has no digits" error, which appears to be an error thrown by the Go scanner.

**Comment by alecthomas** [comment]
Glad you enjoy using it :)

There's no reasonable way to extend it, but you can construct one via an existing text/scanner. There may be a way to configure a text/scanner to do this? If not you'll need to roll your own, which is not too hard.

**Comment by alecthomas** [comment]
Check out the `_examples` folders for some custom lexers.

**Comment by leaanthony** [comment]
Thanks for the quick reply Alec. Is the default lexer available for extending? I'll be honest, I've no idea where to start to recreate it :-)

**Comment by alecthomas** [comment]
You want [this function](https://pkg.go.dev/github.com/alecthomas/participle/v2@v2.0.0-alpha6/lexer#LexWithScanner). It depends on whether the text/scanner can be modified to do what you want. It has some configurability.

**Comment by leaanthony** [comment]
Thanks. I'm happy to just greedily consume the uuid and tried using the `@~` syntax but I'm getting `unexpected token ~`. 
Thing to parse: `uuid(76eceacb-0462-4d94-ac83-423a6793775e)`
Current attempt: `'uuid' '(' @~')' ')'`

**Comment by alecthomas** [comment]
If `~` is a literal you will need to quote it the same way you've done with `uuid`, `(` and `)`, eg. `@'~'`
