### ISSUE TITLE
Bad grammar?

### ISSUE THREAD

**Issue by dzonerzy** [alecthomas/participle#170]
```go
package main

import (
	"fmt"

	"github.com/alecthomas/participle/v2"
	"github.com/alecthomas/participle/v2/lexer/stateful"
)

var configLexer = stateful.MustSimple([]stateful.Rule{
	{Name: `whitespace`, Pattern: `\s+`, Action: nil},
	{Name: `Number`, Pattern: `[\d]+`, Action: nil},
	{Name: `Ident`, Pattern: `[\w.-]+`, Action: nil},
	{Name: `String`, Pattern: `"(?:\\.|[^"])*"`, Action: nil},
	{Name: `Path`, Pattern: `(^[\w\\.:\s]+?\.\w{2,4}$|^\/[a-zA-Z0-9_\/-]*[^\/]$)`, Action: nil},
})

type Config struct {
	Servers []*Server `@@*`
}

type Server struct {
	VirtualHost string      `"server" @Ident "{"`
	Properties  *Properties `@@* "}"`
}

type Properties struct {
	Listen int `"listen" ":" @Ident`
}

var parser = participle.MustBuild(&Config{},
	participle.Lexer(configLexer),
	participle.Unquote("String"),
)

var code = `
server dzonerzy.net {
	listen: 1234
}
`

func main() {
	cfg := &Config{}
	err := parser.ParseString("", code, cfg)
	if err != nil {
		panic(err)
	}
	fmt.Println(cfg.Servers)
}
```

Can you kindly explain me what I'm doing wrong?

**Comment by alecthomas** [comment]
What's the error?

**Comment by dzonerzy** [comment]
`panic: 2:21: invalid input text "{\n\tlisten: 1234\n..."`

Seems like "{" is not matched but should be by String rule

**Comment by alecthomas** [comment]
The string rule only matches quoted strings though? You'll need an "punct" rule to match punctuation.

**Comment by alecthomas** [comment]
Also your path and ident rules overlap, so I suspect path will never match.

**Comment by dzonerzy** [comment]
But the String regex can actually match strings like “:” “{“ and “[“ , is actually needed to add another Punct regex since those are actually covered by String rule?

**Comment by alecthomas** [comment]
I don't understand why you think that. The String regex only matches some text surrounded by double quotes as far as I can tell?

**Comment by dzonerzy** [comment]
Match anything inside “” isn’t “{“ inside double quotes? By reading documentation I found that to match literals lexer must define a rule that match that literal exactly and String rule match that

**Comment by alecthomas** [comment]
You are misunderstanding something, but I'm not sure what. This rule:

```go
	{Name: `String`, Pattern: `"(?:\\.|[^"])*"`, Action: nil},
```

Will match the literal text `"foo"`, `"bar"`, and so on, but will not match `{` because it is not surrounded by double quotes.

**Comment by alecthomas** [comment]
You want a rule something like this:

```go
{Name: `Punct`, Pattern: `[{},:]`, Action: nil},
```
