### ISSUE TITLE
TestInvalidNumbers fails on 32bit with "constant ... overflows int"

### ISSUE THREAD

**Issue by merkys** [alecthomas/participle#176]
I am running tests for participle 0.3.0 ([skeema](https://github.com/skeema/skeema) wants this version as of now) on armhf and i386 architectures, and it seems that the following lines:
https://github.com/alecthomas/participle/blob/612a3e6efbf30ca7c795d5db9cedcac75aef7aa1/parser_test.go#L872-L873
cause test `TestInvalidNumbers` to fail with:
```
src/github.com/alecthomas/participle/parser_test.go:841:70: constant 2147483648 overflows int
src/github.com/alecthomas/participle/parser_test.go:842:43: constant 9223372036854775807 overflows int
```
Maybe 32bit architectures could be detected and these two cases could be skipped on them?

**Comment by alecthomas** [comment]
FWIW these don't indicate a bug in Participle.

You should be able to explicitly cast this to an int64, eg. `int64(math.MaxInt32+1)`. I can't test this, but if it works I'd be happy to accept a PR.

Also out of curiosity, why are you running the Participle tests at all?

**Comment by merkys** [comment]
> FWIW these don't indicate a bug in Participle.

Thanks for confirming.

> You should be able to explicitly cast this to an int64, eg. `int64(math.MaxInt32+1)`. I can't test this, but if it works I'd be happy to accept a PR.

I have adapted your hint in PR#177, and the said test successfully passes.

> Also out of curiosity, why are you running the Participle tests at all?

I have prepared a Debian package for Participle. It is common practice to run tests during build time for Debian packages.
