### ISSUE TITLE
Clarify README: Does participle support custom lexers or not?

### ISSUE THREAD

**Issue by stevegt** [alecthomas/participle#180]
The README [discusses](https://github.com/alecthomas/participle#lexing) writing custom lexers, but then later [says](https://github.com/alecthomas/participle#example-simplenon-stateful-lexer) "The Stateful lexer is now the only custom lexer supported by Participle".

Makes it sound like there's been a recent code change that prevents using custom lexers with participle.  Is writing your own custom lexer (e.g. indent-based as in #20) still supported?

**Comment by stevegt** [comment]
'git blame' says both of those sections were added in the same commit... would it be correct to change "now the only custom lexer supported by Participle" to "now the only custom lexer included with Participle"?

**Comment by alecthomas** [comment]
Sure, sounds reasonable. PRs welcome.

**Comment by stevegt** [comment]
Will do.  Trying to come up with accurate wording while looking through 362b26640fa3dc406aa60960f7d9a5b9a909414e and current, it looks like there is no longer a way to define a grammar using EBNF without writing your own custom lexer -- Stateful only accepts regex-style rules, right?
