### ISSUE TITLE
Unexpected token after recursive capture

### ISSUE THREAD

**Issue by romch007** [alecthomas/participle#182]
I'm trying to implement a Subrip (subtitles) parser, here is my code :
```go
type SubripFile struct {
	SubEntries []*SubEntry `parser:"@@*"`
}

type SubEntry struct {
	N     int             `parser:"@Int"`
	Range *TimestampRange `parser:"@@"`
	Text  string          `parser:"@String"`
}

type Timestamp struct {
	Hours        int `parser:"@Int"`
	Minutes      int `parser:"':' @Int"`
	Seconds      int `parser:"':' @Int"`
	Milliseconds int `parser:"',' @Int"`
}

type TimestampRange struct {
	StartTime *Timestamp `parser:"@@"`
	EndTime   *Timestamp `parser:"'-->' @@"`
}
```

When I test it against this string input : 
```
1
00:41:54,625 --> 00:41:57,625
It's time
```
I get this error : `unexpected token "-" (expected "-->")`.
I isolated the TimestampRange struct and tested this input, `00:41:54,625 --> 00:41:57,625` but got the same error.
Does someone have any idea where my mistake is ? Thanks!

**Comment by alecthomas** [comment]
If you are using the default lexer it produces a one token for each punctuation symbol. ie. -, -, > rather than -->

Your grammar will have to match each token separately.

**Comment by romch007** [comment]
Thank you very much, it works!
