### ISSUE TITLE
TextScannerLexer does not scan comment

### ISSUE THREAD

**Issue by pasunx** [alecthomas/participle#183]
https://github.com/alecthomas/participle/blob/6cd649b84fb3068c3d12dab0dd33a219c601b077/lexer/text_scanner.go#L50-L51

The default `text/scanner.Scanner.Mode` is `GoTokens`
https://github.com/golang/go/blob/bd8009d4392fae3ad148a0fe9adb4ea4ac5ab8d3/src/text/scanner/scanner.go#L208

But `GoTokens` include `SkipComments`
https://github.com/golang/go/blob/bd8009d4392fae3ad148a0fe9adb4ea4ac5ab8d3/src/text/scanner/scanner.go#L73

**Comment by alecthomas** [comment]
That is intentional. You can use the alternate constructor to pass in a scanner configured as desired.

**Comment by alecthomas** [comment]
On mobile at the moment so I don't have the name of the alternate constructor handy, but it's in the same package.

**Comment by pasunx** [comment]
Sorry for the late reply,
But I don't see how to use a custom scanner with DefaultDefinition.

**Comment by pasunx** [comment]
Did you mean these ?
```go
	result := &File{}
	sc := &scanner.Scanner{}
	sc.Init(rd)
	sc.Mode &^= scanner.SkipComments
	lex, err := lexer.Upgrade(lexer.LexWithScanner(append(filename, "")[0], sc))
	if err != nil {
		return nil, err
	}
	err = parser.ParseFromLexer(lex, result)
	return result, err
```
But I think it's too long instead of doing this.
```go
	err := parser.Parse(append(filename, "")[0], rd, result)
```

**Comment by alecthomas** [comment]
That is the correct function yes, but it looks like we need a `LexerDefinition` implementation so that you don't have to pass it to every `Parse()` call. I'll add that.

**Comment by alecthomas** [comment]
Okay give that a shot. eg.

```go
p, err := participle.Build(&grammar{}, participle.Lexer(NewTextScannerLexer(func(s *scanner.Scanner) {
		s.Mode &^= scanner.SkipComments
	})))
```
