### ISSUE TITLE
UnexpectedTokenError not being returned

### ISSUE THREAD

**Issue by asmaloney** [alecthomas/participle#184]
When I call `participle.Parse()` and receive an error, I want to use `participle.Error.Message()` and `participle.Error.Position()` to format the error myself. The problem is I'm not getting an `UnexpectedTokenError`...

I'm doing this:

```go
err := Parse(...)

if err != nil {
	var e *participle.UnexpectedTokenError
	if errors.As(err, &e) {
		fmt.Printf("@@@@ %s\n", e.Message())
	}
}
```

If I output err.Error() it is in fact an unexpected token error:
```
10:22: unexpected token "blat" (expected (SetValue | Pattern))
```

Maybe something isn't returning an `UnexpectedTokenError` properly? Or am I misunderstanding how this is supposed to be used?

**Comment by alecthomas** [comment]
Per the [documentation](https://github.com/alecthomas/participle#error-reporting), Participle returns an error conforming to the `Error` interface, there's no guarantee that a concrete error type will be returned.

**Comment by asmaloney** [comment]
Ah, got it. Thank you!

```go
if err != nil {
	perr, ok := err.(participle.Error)
	if ok {
		fmt.Printf("@@@@ %s\n", perr.Message())
	}
}
```
