### ISSUE TITLE
Errors not checked in ParseString() and ParseBytes()

### ISSUE THREAD

**Issue by asmaloney** [alecthomas/participle#185]
Static analysis shows that the following `err`s aren't checked in `parser.go`:

```go
func (p *Parser) ParseString(filename string, s string, v interface{}, options ...ParseOption) (err error) {
	var lex lexer.Lexer
	if sl, ok := p.lex.(lexer.StringDefinition); ok {
		lex, err = sl.LexString(filename, s)
	} else {
		lex, err = p.lex.Lex(filename, strings.NewReader(s))
	}
	return p.parse(lex, v, options...)
}
```

and

```go
func (p *Parser) ParseBytes(filename string, b []byte, v interface{}, options ...ParseOption) (err error) {
	var lex lexer.Lexer
	if sl, ok := p.lex.(lexer.BytesDefinition); ok {
		lex, err = sl.LexBytes(filename, b)
	} else {
		lex, err = p.lex.Lex(filename, bytes.NewReader(b))
	}
	return p.parse(lex, v, options...)
}
```

`err` is assigned, but never checked, and the p.parse()'s error is going to be returned by these functions.

They should probably be checked and returned before the call to `parse`.

**Comment by alecthomas** [comment]
What static analysis did you use? golangci-lint should have picked this up but didn't for some reason.

**Comment by alecthomas** [comment]
Never mind, I had disabled megacheck years ago but I think whatever it was duplicating has subsequently been removed.

**Comment by alecthomas** [comment]
Thanks for the report!
