### ISSUE TITLE
[Question] Parsing Go

### ISSUE THREAD

**Issue by leaanthony** [alecthomas/participle#187]
Seems like an obvious use case, but can Participle easily parse Go? I'm assuming not as there's no examples?

**Comment by barrettj12** [comment]
I'm also interested to know if anyone's used this library to write a parser for Go (in Go).

**Comment by alecthomas** [comment]
AFAIK nobody has written one, but it should be possible. The only real hurdle is that writing it is quite a lot of work, as even though Go itself is quite a small language relative to others, it's still a complete fully-featured programming language with a lot of syntax.

One option is to automatically generate the parser structs, similar to [this blog post](https://modern-c.blogspot.com/2022/11/producing-go-parser-from-language.html). The linked [EBNF](https://gitlab.com/cznic/gc/-/blob/92f049965c02ee7728e70273142fca3f7090aaf3/v3/internal/ebnf/peg.ebnf) has ~150 rules, so it would be a large amount of work to do this manually.
