### ISSUE TITLE
Optional comments capturing while normally eliding them

### ISSUE THREAD

**Issue by pontaoski** [alecthomas/participle#191]
For https://github.com/tawasprache/kompilierer, I'd like to be able to obtain the text of a comment before an AST node, for documentation generation purposes, while otherwise ignoring them in the parser.

I envision the API looking similar to the Pos/EndPos API:

```go
type Item struct {
    Name `"function" @Ident`
    
    PrecedingComment lexer.Comment
}
```

can parse 

```
// hello!
function hi
```

with the comment and

```
function hi
```

without one

**Comment by pontaoski** [comment]
Uh, add a capture where?

I'm talking about being able to take a grammar like

```go
type File struct {
	Package        string         `"package" @Ident`
	Declarations  []Declaration  `@@*`
}

type Declaration struct {
	FunctionDeclaration *FunctionDeclaration `(@@ |`
	TypeDeclaration    *TypeDeclaration    `@@)`
}

type FunctionDeclaration struct {
	Name                 string         `"funk" @Ident`
	Generischeargumenten []string       `("[" ( @Ident ( "," @Ident )* )? "]")?`
	Formvariabeln        []Formvariable `"(" ( @@ ( "," @@ )* )? ")"`
	Rückgabetyp          *Typ           `(":" @@)?`
	Expression           Expression     `(("=>") | ("->"))? @@`
}
```

and just being able to add a `PrecedingComment lexer.Comment` field to capture whatever comments came immediately before the function declaration without having to modify the entire grammar to explicitly handle comments.

**Comment by alecthomas** [comment]
Check out point "5" here: https://github.com/alecthomas/participle#error-reporting

Basically if you elide tokens with `participle.Elide("Comment")`, but have a field with `Tokens []lexer.Token`, you'll capture all tokens into that field regardless of any grammar.

**Comment by pontaoski** [comment]
Problem with that is that declarations begin capturing at the first keyword, and there's nothing before the keyword I could logically expand to capture the comment for a declaration in.

```
typ Image ist
  a: List[Colour]
beende

/// Hallo!
funk Hallo()
  10
  ```

`typ` begins capturing from `"typ" ... "beende"` and `funk` captures from `"funk" ... Expression`. There's nothing preceding that I could use to expand the capture of the grammars to include preceding comments as tokens.

**Comment by pontaoski** [comment]
> I've considered this in my own parser, but I don't think it is reasonably generalisable. For example, if `/*...*/` style comments are supported they can basically appear at any point. What field would they be captured into if they're in between `funk` and `<Ident>`?

If `<Ident>` was actually `@@` into a struct, I would make it so that it's captured by `PrecedingComment lexer.Comment`.

I would define `PrecedingComment` as "the collection of all comment tokens immediately preceding the first token of this struct".

**Comment by alecthomas** [comment]
But that won't account for the case I described:
```
	Name                 string         `"funk" @Ident`

```
And the source 
```
funk /* yep */ funky
```

**Comment by pontaoski** [comment]
Ah, that fixes it. Thanks!
