### ISSUE TITLE
How to include braces only when "more than one"

### ISSUE THREAD

**Issue by asmaloney** [alecthomas/participle#198]
I have something like the following:

```
Foo  *foo   `parser:"( @@ "`
FooList []*foo `parser:"| '{' @@+ '}')"`
```

This works, but it's a bit messy to handle the `Foo` and `FooList` cases later on - I would prefer to just work with a `FooList`.

Is there a way to allow "one foo without braces BUT require braces if there is more than one"?

I tried what seems to be the obvious:
```
FooList []*foo `parser:"@@ | '{' @@+ '}'"`
```
but that doesn't work. I assume because `@@` won't map to a slice.

**Comment by alecthomas** [comment]
That construct definitely does work, so there must be some other issue. It could be ambiguity in your grammar. Try putting the `'{'` case first so there's no lookahead required.

**Comment by alecthomas** [comment]
But without an error or way to reproduce I can't be sure.
