### ISSUE TITLE
[Feature] Support Join and sub-queries for the SQL parser

### ISSUE THREAD

**Issue by suntong** [alecthomas/participle#209]
Please support Join and sub-queries for the SQL parser.

It's a test of expressiveness and limitation of participle. 

Thanks

**Comment by alecthomas** [comment]
The _examples folder is just that, examples. If they are to be extended, contributions are welcome. That said there are [other](https://github.com/mightyguava/dynamosql/tree/master/parser) examples, including the [minio S3 select parser](https://github.com/minio/minio/blob/master/internal/s3select/sql/parser.go).

**Comment by suntong** [comment]
> there are [other](https://github.com/mightyguava/dynamosql/tree/master/parser) examples, including the [minio S3 select parser](https://github.com/minio/minio/blob/master/internal/s3select/sql/parser.go).

I took a look and neither seems to be able to support Join and sub-queries for SQL `select`.

I'm asking because I don't know if `participle` is capable of supporting them, as that's a test of expressiveness and limitation of participle.

**Comment by alecthomas** [comment]
Participle is a general purpose parser, there's no limitation that would effect this.
