### ISSUE TITLE
Non-capture groups don't work

### ISSUE THREAD

**Issue by testitm** [alecthomas/participle#210]
Hi,
trying to config lexer rule with non-capture group:
```
{"Hash", `(?:#)([0-9A-F]*)`, nil},
```
But output looks like:
```
Hash: "#22"
```
So, if it not wokrs, what is the purpose of such rule in examples folder?
```
{"Comment", `(?:#|//)[^\n]*\n?`},
```

**Comment by alecthomas** [comment]
I'm not sure what you're expecting? Capture groups in the lexer have no special meaning.

If you want to transform a token string parsing you'll need to use ` participle.Map()`.

**Comment by testitm** [comment]
Im expecting something like this 
https://go.dev/play/p/tHz3CLuH2kv
```
s := "#2345"
	re, error := regexp.Compile("(?:#)([0-9A-F]{1,8})")
	if error != nil {
		fmt.Println(error)
	}
	fmt.Println(re.FindStringSubmatch(s)[1])
```

> 2345

**Comment by alecthomas** [comment]
Ah, understood. Unfortunately no, that is not supported. `participle.Map()` will let you arbitrarily transform a token. eg.

```go
participle.Map(func(token lexer.Token) (lexer.Token, error) {
  if strings.HasPrefix(token.Value, "#") { // #.*
    token.Value = token.Value[1:]
  } else { // //.*
    token.Value = token.Value[2:]
  }
  return token, nil
}, "Comment")
```
