### ISSUE TITLE
Elide not eliding?

### ISSUE THREAD

**Issue by asmaloney** [alecthomas/participle#224]
(It's been a while since I messed with my lex/parse, so I'm a bit rusty on participle.)

Using participle v2.0.0-alpha9.

I have a `lexemeComment` which I include as a symbol like this:

```go
func (lexer_def) Symbols() map[string]lexer.TokenType {
	return map[string]lexer.TokenType{
		"Comment":      lexer.TokenType(lexemeComment),
...
```

I ask participle to elide comments & whitespace:
```go
	participle.Elide("Comment", "Whitespace"),
```

I have a struct using `Tokens` like this to capture the tokens for error reporting:

```go
type setStatement struct {
	Set        string  `parser:"'set'"` 
	BufferName string  `parser:"@Ident"`
	Slot       *string `parser:"('.' @Ident)?"`

	To      string    `parser:"'to'"`
	Value   *setValue `parser:"( @@"`
	Pattern *pattern  `parser:"| @@)"`

	Tokens []lexer.Token
}
```

Example input:
```
    do {
        // set foo.bar to 'blat'
        // set foo.bar to 'blat'
        set goal.juddgment to 'pending'
        recall [property: ?obj category ?]
    }
```
Debug output Tokens from example - TOK (line number, columns): (value) (type):
```
TOK (54, 4-6): do (5)
TOK (54, 7-8): { (8)
TOK (55, 8-32): // set foo.bar to 'blat' (3)
TOK (56, 8-32): // set foo.bar to 'blat' (3)
TOK (57, 8-11): set (5)
TOK (57, 12-16): goal (4)
TOK (57, 16-17): . (6)
TOK (57, 17-26): juddgment (4)
TOK (57, 27-29): to (5)
TOK (57, 30-39): 'pending' (7)
TOK (58, 8-14): recall (5)
TOK (58, 15-16): [ (9)
TOK (58, 16-24): property (4)
TOK (58, 24-25): : (8)
TOK (58, 26-26):  (10)
TOK (58, 26-30): ?obj (11)
TOK (58, 31-31):  (10)
TOK (58, 31-39): category (4)
TOK (58, 40-40):  (10)
TOK (58, 40-41): ? (11)
TOK (58, 41-42): ] (9)
TOK (59, 4-5): } (8)
```

Type 3 is my comment type (`lexemeComment`). So far so good.

But when I access `setStatement.Tokens`, it has captured the comments:

```
[]lexer.Token{Token@55:8{3, "// set foo.bar to 'blat'"}, Token@56:8{3, "// set foo.bar to 'blat'"}, Token@57:8{5, "set"}, Token@57:12{4, "goal"}, Token@57:16{6, "."}, Token@57:17{4, "juddgment"}, Token@57:27{5, "to"}, Token@57:30{7, "pending"}}
```

Are the captured Tokens not being elided properly or am I misunderstanding how this works?

**Comment by alecthomas** [comment]
Elided tokens [are included](https://github.com/alecthomas/participle#Errorreporting) in the `Tokens` field in v2. You can also now explicitly match elided comments if you reference them directly, eg. `Comment Int` vs. `Int`, both will work. 

If you want to exclude them your lexer will need to do it. For example the included stateful lexer will [drop tokens](https://github.com/alecthomas/participle/blob/master/lexer/doc.go#L12) starting with a lower case letter.

**Comment by asmaloney** [comment]
> will be automatically populated with all tokens captured by the node, including elided tokens.

My apologies - I'm not quite sure how I missed this when I read it... _yesterday_ 😄 

It feels strange that it captures them at the beginning (and end) of the match, but I can work around it.

Thanks Alec!

**Comment by alecthomas** [comment]
> It feels strange that it captures them at the beginning (and end) of the match, but I can work around it.

WDYM?

**Comment by asmaloney** [comment]
> WDYM?

I'm declaring `Tokens` within a struct (`setStatement` above) to capture its tokens, yet it's including tokens outside the "scope" of said struct (`Set` to `Pattern` above).
