### ISSUE TITLE
EndPos with text/scanner is the same as Pos

### ISSUE THREAD

**Issue by adaam2** [alecthomas/participle#225]
Hey there,

Great package! :) 

Using the built in text scanner lexer, I am finding that the values for `Pos` / `EndPos` are the same (e.g the column is the same for a token "foo" and therefore it only captures the "f".) Am I just capturing my tokens incorrectly, or is it a deficiency of the `text/scanner` implementation?

Thanks!

**Comment by alecthomas** [comment]
The range is a half open interval [b, e), so you'll need to include the token length.

**Comment by alecthomas** [comment]
Glad you like it and thanks BTW!
