### ISSUE TITLE
Use tag on structure

### ISSUE THREAD

**Issue by kevinhassan** [alecthomas/participle#23]
I'm trying to use encoding/json with it's tags to change attributes' name of my structure. But the issue is that "json token is not recognized". 
How could I escape json tag ?

**Comment by alecthomas** [comment]
I'd need an example to be sure, but the participle grammar can be in its own standard-style tag eg.

```go
type User struct {
  Name string `participle:"@Ident" json:"name"`
}
```

**Comment by kevinhassan** [comment]
```golang
type Statement struct {
	RuleClause   *RuleClause   `participle:"'RULE' @@"`
	DefineClause *DefineClause `participle:"'[' @@ ']'"`
	AsClause     *AsClause     `participle:"'AS' @@"`
}
```

If I write in the standard-tag, I will have the following error : 
> panic: Statement: RuleClause: unknown token type "participle"

**Comment by kevinhassan** [comment]
Ok I made a mistake it's working with the following tags :

```golang
type Statement struct {
	RuleClause   *RuleClause   `parser:"'RULE' @@" json:"rule"`
	DefineClause *DefineClause `parser:"'[' @@ ']'" json:"define"`
	AsClause     *AsClause     `parser:"'AS' @@" json:"as"`
}
``` 
But an other problem appears, when adding some attributes (Value, Events) to my structure : 

```golang
type Premise struct {
	AmountClause *AmountClause `parser:"(@@|" json:"amount"`
	HappenClause *HappenClause `parser:"@@)" json:"happen"`
	FromClause   *FromClause   `parser:"['FROM' '(' @@ ')']" json:"from"` // Optional clause
	AtClause     *AtClause     `parser:"['AT' '(' @@ ')']" json:"at"`     // Optional clause
	Value        int           `json:"value"`
	Events       []*Event      `json:"events"`
}
```
> panic: Statement: RuleClause: DefineClause: Expressions: Expression: Premise: Premise: AmountClause: unknown token type "json"

**Comment by alecthomas** [comment]
The `Value` and `Events fields need a `parser:""` tag, even if it is empty.

**Comment by kevinhassan** [comment]
This what I thought so I already tried with the following code : 
```golang 
type Premise struct {
	AmountClause *AmountClause `parser:"(@@|" json:"amount,omitempty"`
	HappenClause *HappenClause `parser:"@@)" json:"happen,omitempty"`
	FromClause   *FromClause   `parser:"['FROM' '(' @@ ')']" json:"from,omitempty"` // Optional clause
	AtClause     *AtClause     `parser:"['AT' '(' @@ ')']" json:"at,omitempty"`     // Optional clause
	Value        int           `parser:"" json:"value"`
	Events       []*Event      `parser:"" json:"events"`
}
``` 
>panic: Statement: RuleClause: DefineClause: Expressions: Expression: Premise: Premise: AmountClause: unknown token type "parser"

**Comment by alecthomas** [comment]
Ah right, they can't be empty. You can't have empty fields in a Participle grammar.

**Comment by alecthomas** [comment]
Note that I'm not saying that there isn't a potential use case for having empty fields, or that this failure behaviour is desirable, just that it is the current situation.

**Comment by alecthomas** [comment]
I've done a bunch of changes recently, can you try again?

**Comment by kevinhassan** [comment]
I tried with the same sample of code, but I have the same error.

**Comment by alecthomas** [comment]
Can you provide a minimal reproducible example that I can run and test against?

**Comment by kevinhassan** [comment]
I recently updated the participle lib on your latest commit and it's working when I write 
```go
parser:"" json:"events"`
```
Thank you very much, good job ! :clap:
