### ISSUE TITLE
Union does not work for pointer type

### ISSUE THREAD

**Issue by itstarsun** [alecthomas/participle#255]
https://go.dev/play/p/CWC44DlcCl5

**Comment by alecthomas** [comment]
Ah yes, interesting. I have a fix half done, will get it in today hopefully.

**Comment by alecthomas** [comment]
Tagged v2.0.0-beta.5 with the fix.

**Comment by petee-d** [comment]
@alecthomas while making coverage for this in #213, I discovered this fix wasn't correct. https://github.com/alecthomas/participle/commit/49f4822e#diff-5bc2d8471b75bfdf044ca005bc151f75b27c820ab857ef639ffe1124405c3c47R114 - `vals` always has length 0 (no match) or 1 (match, will be the result of `strct.Parse`, a single struct value). There is no correlation between the indexes of `vals` and `u.members`. This fix ends up only looking at the first union option and makes either all the options pointers, or none.

To see the bug in action, try modifying `TestParserWithUnion`. In the `participle.Union` option, change `AMember2{}` to `(*AMember2)(nil)` - it changes nothing. Or make just `AMember1` into a pointer - then it uses pointers for both of them.
