### ISSUE TITLE
Lexer match but not consume?

### ISSUE THREAD

**Issue by yonderblue** [alecthomas/participle#259]
Is it possible to have the lexer match something like `OR` but also matches `OR^` or `OR ` or any kind of punctation but still only consume `OR` so the lexer can handle the next char with the next token?

**Comment by yonderblue** [comment]
I would have used regex lookahead but that isn't available I believe.

**Comment by alecthomas** [comment]
No, that should be done by the parser.

**Comment by alecthomas** [comment]
To clarify, the lexer should be as straightforward as possible, with no ambiguity between the tokens.

**Comment by yonderblue** [comment]
@alecthomas thanks for the response. Here is a small runnable example. Changing the OR pattern to `(?i)or\b` solves the issue, but is another form of lookahead that relies on the definition of `\w`. What if I wanted `-` to also be considered in `\w`? Do you suggest a different approach?
```
package main

import (
	"fmt"

	"github.com/alecthomas/participle/v2"
	"github.com/alecthomas/participle/v2/lexer"
)

func main() {
	s := "mars or earth Orbit"

	dumpLex(lexDef, s)

	p, err := parser.ParseString("", s)
	if err != nil {
		panic(err)
	}
	fmt.Printf("PARSE %+v\n", p)
}

type parse struct {
	Texts []text `@@*`
}

type text struct {
	Or    bool     `( @Or`
	Texts []string `| @Plain+ )`
}

var (
	lexDef = lexer.MustSimple([]lexer.SimpleRule{
		{"Or", `(?i)or`},
		{"Plain", `\S+`},
		{"whitespace", `\s+`},
	})
	parser = participle.MustBuild[parse](participle.Lexer(lexDef))
)

func dumpLex(def *lexer.StatefulDefinition, s string) {
	fmt.Println("STRING", s)
	fmt.Println("SYMBOLS", def.Symbols())

	lex, err := def.LexString("", s)
	if err != nil {
		panic(err)
	}

	tokens, err := lexer.ConsumeAll(lex)
	if err != nil {
		panic(err)
	}

	for _, t := range tokens {
		fmt.Printf("TOKEN type=%v value=%v\n", t.Type, t.Value)
	}
}
```
