### ISSUE TITLE
Document AllowTrailing 

### ISSUE THREAD

**Issue by mikaelhg** [alecthomas/participle#267]
Please document AllowTrailing and its suggested use. 

My use case for it was that I wish to parse merely the header of a very large file.

**Comment by mikaelhg** [comment]
Also, please document the use case where you wish to terminate a stateful lexer before the EOF.

**Comment by alecthomas** [comment]
The stateful lexer can't be terminated before EOF. AllowTrailing is documented [here](https://pkg.go.dev/github.com/alecthomas/participle/v2#AllowTrailing).
