### ISSUE TITLE
Proposal: Order independent parsing

### ISSUE THREAD

**Issue by martin31821** [alecthomas/participle#29]
I stumbled across a minor issue which is might worth further discussion.

I think it would be good to have a possibility to declare substructs as order independent.

## Use Case

I have a language which is influenced by hcl, but has support for nested blocks with special names, the idea is to support an arbitrary order for those sub-blocks, but have the blocks only being generated either zero or one time.

## Solution proposal

Introducing a new parser primitive like `{ }` for repetition (e.g. using `<>`) which defines a `Set` of arguments, which can be parsed order independent.

**Comment by martin31821** [comment]
The closest I can think of is something like this:
```ebnf
x = (a b c) | (a c b) | (b a c) | (b c a) | (c a b) | (c b a);
a = "foo" "{" { k "=" v "," } "}";
b = "bar" "{" { k "=" v "," } "}";
c = "baz" "{" { k "=" v "," } "}";
k = IDENTIFIER;
v = STRING;
```

basically the idea is to have multiple rules which can occur in any order but each rule may only occur once, so the following is valid:

```hcl
foo {
a="b",
c="d",
}
bar {
a="b",
c="d",
}
```
but this is not:
```hcl
foo {
a="b",
c="d",
}
foo {
e="f",
}
```

I'd like to specify something like this as semantically equivalent of the above:
```ebnf
x = <a b c>;
a = "foo" "{" { k "=" v "," } "}";
b = "bar" "{" { k "=" v "," } "}";
c = "baz" "{" { k "=" v "," } "}";
k = IDENTIFIER;
v = STRING;
```

**Comment by alecthomas** [comment]
Ah, ok, interesting idea. I think that in the interest of keeping the grammar syntax simple (and sticking largely with EBNF), that it's fine to enforce this in semantic analysis, after parsing.
