### ISSUE TITLE
More information in errors

### ISSUE THREAD

**Issue by ricochet1k** [alecthomas/participle#290]
I would really like the ability to introspect more into the parser's state when it fails in order to generate better error messages.

For example, if I have a String grammar that looks something like
```go
type String struct {
	Fragments []Fragment `parser:"\"\\\"\" @@* \"\\\"\""` // because '\"' doesn't work :/
}
```

if I leave off the final `"` the error I get is `unexpected token "<EOF>" (expected "\"")` and there appears to be no way of looking at a partial parse state to find where the first `"` was. I'd love if the parser could somehow return a stack of incomplete productions that could be inspected from the returned error. Or even better, let a production include a `Error participle.Error` field, which if not-nil signifies that the enclosing production is incomplete somehow, and then it would be returned from `.Parse` instead of an empty value.

**Comment by alecthomas** [comment]
When constructing a parser, Participle will return the stack of types leading up to the failed structure. It doesn't currently narrow it down to the field though.

eg. https://go.dev/play/p/zvJv_w4YfJx gives

```
panic: Fragments: <input>:1:11: literal not terminated
```

I think in this case it's just missing the inner struct in the trace.

**Comment by ricochet1k** [comment]
Sorry, that comment was misleading, and actually wasn't what I was talking about.

What I'm referring to is using a correct and working parser definition to parse a file where the contents are an incomplete string: https://go.dev/play/p/bVqcFvYlHkT

**Comment by alecthomas** [comment]
Ah I see. In that case you want the `Trace()` option: https://go.dev/play/p/rI4Iz1mdWIn

**Comment by alecthomas** [comment]
Also, in the case of partial failure, the returned structure will be populated up to the point of the last successful match. I've found this useful. This is covered in the [docs](https://github.com/alecthomas/participle#error-reporting) BTW.
