### ISSUE TITLE
Declaring field parse order

### ISSUE THREAD

**Issue by rmfitzpatrick** [alecthomas/participle#291]
This (extremely helpful) library may be currently incompatible with projects enforcing [fieldalignment](https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/fieldalignment) in the likely chance their ast fields aren't defined in an already optimal order. Is there an existing option or feature that allows using something like reflect's `Type.FieldByName()`?

```go
type AST struct {
  Two string `@Ident`
  One string `@Ident`
}

func (a AST) ParseOrder() []string {
  return []string{"One", "Two"}
}
```

**Comment by alecthomas** [comment]
There is no option for this, no.

While I appreciate the use case, it's pretty niche, and reordering the fields would make understanding the grammar _extremely_ difficult.

**Comment by rmfitzpatrick** [comment]
I've not had immediate luck in finding how to disable the analyzer for a given package/file and understand the potentially poor experience with such a helper method. Another thought would be to allow defining a parser from an ebnf grammar where terminals are field names to not require struct tags at all, but that's probably much more complicated.

**Comment by alecthomas** [comment]
I use golangci-lint which I believe includes this. It supports a //nolint:XXX directive

**Comment by rmfitzpatrick** [comment]
Thanks, though I'm referring to its cmd invocation `fieldalignment -fix` and will just have to enumerate paths rather than `./...`.
