### ISSUE TITLE
Simple example fails with `unexpected token "<EOF>"`

### ISSUE THREAD

**Issue by Dogacel** [alecthomas/participle#292]
Here is the simple example I am trying to use:

```go
// nolint: govet, golint
package main

import (
	"github.com/alecthomas/participle/v2"
	"github.com/alecthomas/participle/v2/lexer"
	"github.com/alecthomas/repr"
)

type Text struct {
	Pos lexer.Position

	First string `  @ident `
}

var (
	testParser = participle.MustBuild[Text](
		participle.Lexer(
			lexer.MustSimple(
				[]lexer.SimpleRule{
					// Letters and Digits
					{"letter", `[a-zA-Z]`},
					{"decimalDigit", `[0-9]`},

					// Identifiers
					{"ident", `letter ( letter | decimalDigit )*`},
				}),
		),
	)
)

func main() {
	proto, err := testParser.ParseString("string_test", `something`)

	if err != nil {
		panic(err)
	}

	repr.Println(proto, repr.Hide(&lexer.Position{}))
}

```

And it is giving me the error:
```
panic: string_test:1:10: unexpected token "<EOF>"
```

I have tried adding the token for `<EOF>` but couldn't manage to do it. Also I couldn't find any documentation regarding this.

I am using MacOS w/ go 1.19.3

**Comment by alecthomas** [comment]
Your lexer is not correct. Each entry is a self-contained regex pattern.

**Comment by alecthomas** [comment]
Try looking through the _examples folder.

**Comment by Dogacel** [comment]
> Your lexer is not correct. Each entry is a self-contained regex pattern.

Got it, I am hoping this issue will guide other who also see the same issue.

My observation is: If lever fails to parse any rule it seems like this EOF error is thrown.
