### ISSUE TITLE
Missing wildcard

### ISSUE THREAD

**Issue by lmrcarneiro** [alecthomas/participle#293]
Hello, first of all thanks for the awesome project.

I think I noticed some missing wildcards on master/_examples/expr2/main.go.
On equality, comparison and addition structures the * symbol is present on the commentary but not on the struct definition. Maybe the ']' symbol symbolizes that? I'm not sure...

Example:
`// equality       → comparison ( ( "!=" | "==" ) comparison )* ;`

Goes from:
```
type Equality struct {
	Comparison *Comparison `@@`
	Op         string      `[ @( "!" "=" | "=" "=" )`
	Next       *Equality   `  @@ ]`
}
```

To:
```
type Equality struct {
	Comparison *Comparison `@@`
	Op         string      `[ @( "!" "=" | "=" "=" )`
	Next       *Equality   `  @@ ]*`
}
```
Note the wildcard symbol on the Next component of the struct.
Repeat as needed on other structs.

Also, this is my first issue on github, so sorry if I'm missing something

**Comment by lmrcarneiro** [comment]
Nevermind... Turns out that [expr] equals (expr)?*, is that right?

**Comment by alecthomas** [comment]
That is correct, though it is no longer supported so if you want to send a PR changing it to `()*` that would be appreciated.
