### ISSUE TITLE
Broken examples

### ISSUE THREAD

**Issue by shabinesh** [alecthomas/participle#30]
Example code inside [_examples](https://github.com/alecthomas/participle/tree/master/_examples) isn't compatible with the newer API which requires a lexer instance to be passed to the `parser.Build()`

while running [this](https://github.com/alecthomas/participle/blob/master/_examples/toml/main.go)  example error returned is 
```go
./ex.go:71:33: not enough arguments in call to participle.Build
	have (*TOML)
	want (interface {}, lexer.Definition)
```

**Comment by alecthomas** [comment]
I suspect you are running new examples against an older installed version of Participle. The interface to `parser.Build()` has changed and is now [this](https://godoc.org/github.com/alecthomas/participle#Build).

**Comment by shabinesh** [comment]
Thanks @alecthomas
