### ISSUE TITLE
AST until error

### ISSUE THREAD

**Issue by ReneHollander** [alecthomas/participle#31]
Currently, if an error occurs parsing a string, no AST will be returned. Is it possible to return the AST until an error occured? How much work do you think it would take to implement this?

I want to use my grammer to provide suggestions for the next token based on the current context.

**Comment by alecthomas** [comment]
I think that should be possible, but how will you identify where in the AST the error occurred?

**Comment by alecthomas** [comment]
This has [been implemented](https://github.com/alecthomas/participle/commit/47e835b8cd50d9ad561f043f6ee618c26fc81181).
