### ISSUE TITLE
Make tags to be reflect.StructTag.Get compatible

### ISSUE THREAD

**Issue by mkrasuski** [alecthomas/participle#32]
It would be useful to have possibility to use tag syntax compatible with `reflect.StructTag.Get` i.e.
```go
type Cmds struct {
   Cmds []Cmd     `parse: "{ @@ }"`
}
```
It would not bother with other features based on tags. Nice, if it could be an option, parallel to current  syntax.

**Comment by mkrasuski** [comment]
Sorry, my mistake... this option is already there, but not used in samples... just a small note in docs. Great.

**Comment by alecthomas** [comment]
👍

**Comment by chenzhekl** [comment]
@mkrasuski Could you elaborate it a bit more? I am facing the same issue.

**Comment by chenzhekl** [comment]
Finally got it. For others facing the same problem, just key the label with "parser".

e.g. Rewrite 

```
type Grammar struct {
  Hello string `@Ident`
}
```

to 

```
type Grammar struct {
  Hello string `parser:"@Ident"`
}
```

silence the warning.
