### ISSUE TITLE
Overflow parsing uint64

### ISSUE THREAD

**Issue by hyprnick** [alecthomas/participle#34]
There isn't any error handling in this code: https://github.com/alecthomas/participle/blob/master/nodes.go#L302-L307

I'm trying to reject values larger than 2^64.  When I add some logging in that block, I get this:  

```
strconv.ParseUint: parsing "18446744073709551616": value out of range
```

However, the value I get is 1 with no parsing errors.

**Comment by incognick** [comment]
I can make a PR if that will help. Would just need some direction.

**Comment by alecthomas** [comment]
That would be appreciated.

It just needs calls to [panicf()](https://github.com/square/misk/blob/master/misk-hibernate/src/main/kotlin/misk/hibernate/DataSourceConfig.kt) in an else clause for each one.

If you don't get to it I will soonish.

**Comment by alecthomas** [comment]
Actually after taking a bit of a closer look I realised this is (somewhat) deliberate. If Participle encounters non-numeric tokens being captured into numeric fields it treats the field as a counter and increments it. That is useful for certain types of grammar features. On the other hand, it is also very confusing when you don't want that behaviour.

I think I will remove that feature. It can be replicated with a custom `Capture` implementation anyway.
