### ISSUE TITLE
Pos field not automatically populated for structs implementing Capture()

### ISSUE THREAD

**Issue by texttheater** [alecthomas/participle#35]
It appears that structs that implement Capture() do not get their `Pos lexer.Position` field automatically populated like other grammar nodes. The Capture method cannot do this either, because it does not get passed any positional information. Is this intentional or an oversight?

**Comment by alecthomas** [comment]
A bug! The check for Capture must take place before the Pos update. I’ll push up a fix today, thanks for reporting!

**Comment by alecthomas** [comment]
Fixed in f14a17d2994cc0948ed65518c1bdc757c8750868.

**Comment by texttheater** [comment]
Thank you very much!
