### ISSUE TITLE
Railroad diagram command

### ISSUE THREAD

**Issue by SlashScreen** [alecthomas/participle#360]
The readme mentions a railroad diagram command using the EBNF produced by `Parser.String()`. How do I use this? The link provided simply leads to blob.master, which doesn't tell me anything, unless I'm missing something.
I'd like to use it to debug some odd behavior of my grammar.

**Comment by alecthomas** [comment]
Ah odd. The command is here: https://github.com/alecthomas/participle/tree/master/cmd/railroad

**Comment by SlashScreen** [comment]
Thanks. Pressing control-D doesn't seem to do anything, only add ^D. Am I missing something?

**Comment by alecthomas** [comment]
What's Ctrl-D got to do with Railroad?

**Comment by alecthomas** [comment]
Fixed the link in the README

**Comment by SlashScreen** [comment]
It simply places ^D at the end, rather than stopping the input and proceeding with the program.
![image](https://github.com/alecthomas/participle/assets/12375239/a46d46db-74dc-447c-85a3-cf80bc9f2aec)

**Comment by SlashScreen** [comment]
> What's Ctrl-D got to do with Railroad?

The instructions say `(Use control-D to end input)` (https://github.com/alecthomas/participle/blob/6260c0afa1e9d4138cc52f8e43679ef0f2c5258d/cmd/railroad/main.go#L180)

**Comment by SlashScreen** [comment]
@alecthomas as said here, it's not completely clear how to use railroad. I don't know how to end input, despite following instructions.
