### ISSUE TITLE
Question: Are participle.Parser instances thread-safe?

### ISSUE THREAD

**Issue by bradosg** [alecthomas/participle#375]
Once a participle.Parser has been created, is it safe to call Parse(), ParseBytes(), etc. from multiple go routines at the same time?  (Or do I need to make a pool of participle.Parser instances.)

I didn't see anything in the documentation about this, and there's enough interesting stuff going on internally that is wasn't clear to me by skimming the source either.

Any info on this would be helpful.  Thanks in advance.

**Comment by alecthomas** [comment]
Yes, parser instances are thread safe.
