### ISSUE TITLE
Handling Booleans bug

### ISSUE THREAD

**Issue by haski007** [alecthomas/participle#376]
In cases when we need to parse "true" or "false" into bool in examples  you use :
```Bool     *bool    `|  @("true" | "false")```
but this never handles right: in all cases "true" or "false" in our string - we will get true all the time

**Comment by alecthomas** [comment]
Correct. This is discussed in the [README](https://github.com/alecthomas/participle#capturing-boolean-value).

**Comment by haski007** [comment]
My bad.
Here is issue with example of .toml parser:
`false` can't be captured
field is:
```
Bool     *bool    `| (@"true" | "false")`
```
for this file:
```
# This is a TOML document.
test = false
test2 = true
```
We will get:
```
&main.TOML{
  Pos: Position{Filename: "t.toml", Offset: 27, Line: 2, Column: 1},
  Entries: []*main.Entry{
    {
      Field: &main.Field{
        Key: "test",
        Value: &main.Value{
        },
      },
    },
    {
      Field: &main.Field{
        Key: "test2",
        Value: &main.Value{
          Bool: &true,
        },
      },
    },
  },
}
```
Or it works as planned ?

**Comment by alecthomas** [comment]
It's just a bug in the TOML example. If you could send a PR that would be welcome.
