### ISSUE TITLE
PAnic vs return nil in validate function

### ISSUE THREAD

**Issue by akvlad** [alecthomas/participle#377]
Hello.
I'm trying to build the participle library inside a wasm app.
Among some "avoidable" minor issues I have noticed issue with `panic("done")` inside the validate function
https://github.com/alecthomas/participle/blob/master/validate.go#L45
Somehow tiny-go doesn't process the deferred recover() call in this case.
Can it be replace with `return nil` ?

**Comment by alecthomas** [comment]
Possibly. If the tests pass it should be fine.

**Comment by alecthomas** [comment]
Closing this, no PR.
