### ISSUE TITLE
Production orders and weird bug

### ISSUE THREAD

**Issue by ACedric** [alecthomas/participle#38]
Hi,

I'm currently having some weird issues on my current project.
I have reduced the problem to this extremly simple nominal use case (which still doesn't work) : 

```go
package main

import (
	"log"

	"github.com/alecthomas/participle"
	"github.com/alecthomas/participle/lexer"
	"github.com/alecthomas/participle/lexer/ebnf"
	"github.com/alecthomas/repr"
)

type Query struct {
	Number string ` @MyNumber `
}

func main() {
	queryLexer := lexer.Must(ebnf.New(`
		MyLabel = "0" .
		MyNumber = "0" .
	`))
	queryParser := participle.MustBuild(
		&Query{},
		participle.Lexer(queryLexer),
	)

	ast := &Query{}
	err := queryParser.ParseString("0", ast)
	if err != nil {
		log.Println(err)
	} else {
		repr.Println(ast)
	}
}
```
On execution :
```
$ go run main.go
2018/11/18 18:26:57 <source>:1:1: expected <mynumber> but got "0"
```

The weird thing is, when you swap `MyLabel` and `MyNumber` declaration in ebnf, it works.
```go
	queryLexer := lexer.Must(ebnf.New(`
		MyNumber = "0" .
		MyLabel = "0" .
	`))
```
```
$ go run main.go
&main.Query{
  Number: "0",
}
```
This obviously leads to a lot more annoying issues when processing larger and more complex ebnf grammar.
Am I missing something about participle usage or ebnf declaration ?

Best Regards,

**Comment by alecthomas** [comment]
Tokenisation is completely independent from parsing. For your expectation to hold true the parser would need to tell the lexer what token it expects next, but that’s not what happens. The lexer tokenises based on the order of the productions.

**Comment by alecthomas** [comment]
This is identical to how regular expressions work.

**Comment by alecthomas** [comment]
Here’s a good example: if you changed that grammar to be “0” (ie. a literal token match), how would it know which token to use?
