### ISSUE TITLE
Request: streaming parser support

### ISSUE THREAD

**Issue by tamerh** [alecthomas/participle#39]
Hi,

I have relatively big compressed xml files with different schemas. And i used antlr with java for this purpose and worked well. I was wondering is participle also suitable for this ? For example can i iterate through particular xml elements while parsing?

Thanks

**Comment by alecthomas** [comment]
Hi there. You could definitely write an XML parser in Participle, but it would probably be simpler to use a dedicated XML parser like [etree](https://github.com/beevik/etree)?

**Comment by alecthomas** [comment]
> For example can i iterate through particular xml elements while parsing?

If this is asking whether Participle supports streaming parsing, then the answer is no. Participle returns a full parse tree from a single call.

**Comment by tamerh** [comment]
Hi thanks for clarifying and suggestion. Yes i need streaming parsing. I have tried with go [encoding/xml](https://golang.org/pkg/encoding/xml/) package but unfortunately it is [slow](https://github.com/golang/go/issues/21823) and i guess etree library also on top of the encoding/xml package.that's why i looked alternatives.

So i am planning to write my own parser/lexer similarly mentioned in this [article](https://blog.gopheracademy.com/advent-2014/parsers-lexers/) although i wouldn't prefer.
thanks again.

**Comment by alecthomas** [comment]
I wonder if Participle could be modified so that if it encounters a field that's a channel it will stream the results into that channel. That would be relatively straightforward to implement too.

eg. Given the grammar:

```go
type XML struct {
  Tokens []*Token `@@*`
}
```

If it was converted to:

```go
type XML struct {
  Tokens chan *Token `@@*`
}
```

This might be a bit too much magic though.

**Comment by alecthomas** [comment]
Hmm, maybe it could be restricted to the top-level. eg.

```
type Token struct {
}

func main() {
  parser := participle.MustBuild(chan *Token)
  
  tokens := make(chan *Token)
  err := parser.Parse(r, &tokens)
  for token := range tokens {
    // ...
  }
}
```

I'm not sure how it would deal with errors though. The parser might need `Error() error` method.

**Comment by alecthomas** [comment]
See [README](https://github.com/alecthomas/participle#streaming) for details.
