### ISSUE TITLE
Unable to install lexer generator

### ISSUE THREAD

**Issue by gaiaz-iusipov** [alecthomas/participle#393]
The problem caused by additional `cmd/participle/go.mod` file:

```shell
go install github.com/alecthomas/participle/v2/cmd/participle@2.1.1
go: github.com/alecthomas/participle/v2/cmd/participle@2.1.1: github.com/alecthomas/participle/v2/cmd/participle@2.1.1: invalid version: unknown revision 2.1.1
```

Also `scripts/participle` should be updated, required module version is missing:

```shell
go install github.com/alecthomas/participle/v2/cmd/participle
go: 'go install' requires a version when current directory is not in a module
	Try 'go install github.com/alecthomas/participle/v2/cmd/participle@latest' to install the latest version
```

**Comment by alecthomas** [comment]
`cmd/participle/go.mod` is not designed to be installed remotely, as it has a replace directive. If you need static binaries they're available on the releases page.

Also  `scripts/participle` works fine for me:

```
🐚 ~/dev/participle $ ./scripts/participle --help
Usage: participle <command>

A command-line tool for Participle.

Flags:
  -h, --help       Show context-sensitive help.
      --version

Commands:
  gen lexer <package> [<lexer>]
    Generate a lexer.

Run "participle <command> --help" for more information on a command.
```

**Comment by gaiaz-iusipov** [comment]
> is not designed to be installed remotely

But why limit installation and execution? Virtually any Go module is available for execution with a simple 'go run' command.

For example it would be nice to have something like:

```go
//go:generate go run github.com/alecthomas/participle/v2/cmd/participle@2.1.1 gen lexer ...
```

**Comment by alecthomas** [comment]
Because it complicates the release process, which is currently: tag a commit.

The command is a separate module to avoid polluting Participle's dependencies. Without the replace, a release would entail updating the cmd's go.mod file to point to the future version, committing it, then tagging that commit with that version.

**Comment by gaiaz-iusipov** [comment]
The idea is to completely remove cmd/participle/go.mod, not just the replace directive in it. This way, the release process will not change.

In my opinion, the question boils down to not having unnecessary dependencies. I believe that having the ability to use the utility via go run / go install is more important.

Besides, Go binary does not include unused dependencies.

**Comment by alecthomas** [comment]
Well, we'll agree to disagree.
