### ISSUE TITLE
Recognize longest valid token with regexp lexer

### ISSUE THREAD

**Issue by mewmew** [alecthomas/participle#4]
The regexp lexer currently returns the first valid token (based on the order of the regexp alternatives), rather than the longest valid token.

For instance, the input source `i32` is lexed as the two tokens `"i"` and `"32"` rather than a single and longer token `"i32", given the following lexer regexp

```go
	def, err := lexer.Regexp(
		`(?P<Ident>[a-z_]+)` +
			`|(?P<IntType>i\d+)` +
			`|(\s+)` +
			`|(?P<Number>\d+)`,
	)
```

The same input source is lexed as `"i32" given the following lexer regexp:

```go
	def, err := lexer.Regexp(
		`(?P<IntType>i\d+)` +
			`|(?P<Ident>[a-z_]+)` +
			`|(\s+)` +
			`|(?P<Number>\d+)`,
	)
```

**Comment by alecthomas** [comment]
Unfortunately this behaviour is a product of the regexp library, and not something I can control.
