### ISSUE TITLE
Several examples don't compile

### ISSUE THREAD

**Issue by carlpett** [alecthomas/participle#40]
When trying to understand why my own parser doesn't work, I tried building the examples to better interact with something that should work. However, several don't build:

```
# github.com/alecthomas/participle/_examples/basic
./main.go:33:26: not enough arguments in call to participle.UseLookahead
        have ()
        want (int)
```

```
# github.com/alecthomas/participle/_examples/ini
./main.go:44:88: cannot use iniLexer (type lexer.Definition) as type string in argument to participle.Unquote
```

```
# github.com/alecthomas/participle/_examples/expr2
./main.go:71:66: not enough arguments in call to participle.UseLookahead
        have ()
        want (int)
```

Would it make sense to build the examples as part of CI to ensure they stay up-to-date when there are changes?

**Comment by alecthomas** [comment]
Yes that is definitely a good idea!

**Comment by alecthomas** [comment]
Though now that I try it, I recall why I didn't do it. They're in `_examples` so their dependencies don't get pulled in to participle, but that also means that `go test ./_examples/...` does not work.

**Comment by carlpett** [comment]
Nice work, thanks!
