### ISSUE TITLE
Using interface as type

### ISSUE THREAD

**Issue by zubazuba** [alecthomas/participle#41]
Hei, first of all - thank you for creating such a great parser @alecthomas!

I wonder if it would be possible to support interfaces, e.g:

```
type Example struct {
  Value interface{} `@Anything`
}
```

Currently this returns an error: `unsupported field type interface {} for field Anything`

I need this because I want to create a two tier parsing.

**Comment by alecthomas** [comment]
You're welcome!

I don't see how that would work in practice, as Participle constructs the fields itself. With an empty interface it will never know what to construct.

If you want to customise parsing there are a couple of options: the [Capture](https://godoc.org/github.com/alecthomas/participle#Capture) interface and the [Parseable](https://godoc.org/github.com/alecthomas/participle#Parseable) interface. The former can be used to process tokens captured by the grammar (eg. `@String`) while the latter can be used to capture anything directly from the lexer.

**Comment by alecthomas** [comment]
Something like this:

```go
type AST struct {
  Colour *Colour `@Ident`
}

type Colour struct {
  Colour string
}

func (c *Colour) Capture(tokens []string) error {
  if tokens[0] != "red" {
    return fmt.Errorf("colour must be red")
  }
  c.Colour = tokens[0]
  return nil
}
```

**Comment by zubazuba** [comment]
Thank you, I will try it.
