### ISSUE TITLE
Using chroma for lexers?

### ISSUE THREAD

**Issue by pombredanne** [alecthomas/participle#51]
It would be awesome to have an adapter to use any chroma lexer as a lexer here. This would make creating quick parsers for known languages much straightforward.

**Comment by alecthomas** [comment]
Unfortunately that's not really feasible.

Chroma lexers are more akin to hybrid lexer/parsers (a bit like PEG), in that they include both tokenisation and FSM in a single structure. Participle is much more traditional in that it clearly delineates tokenisation and parsing.

It may be theoretically possible, but I think the amount of work required would be significant.
