### ISSUE TITLE
invalid token [ (hard bracket)

### ISSUE THREAD

**Issue by Strosel** [alecthomas/participle#53]
This might be a stupid question but here goes

im trying to parse PlainMusic as described [here](https://pellejuul.github.io/posts/2017/03/12/writing-music-in-plain-text.html) using the example of  *mary had a little lamb* at the bottom of the page.

my code looks like this:
```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/alecthomas/participle"
	"github.com/alecthomas/participle/lexer"
)

type PlainMusic struct {
	Instruments []Instrument `@@*`
}

type Instrument struct {
	Name          string `("[instrument: " @Ident "]")?`
	Clef          rune   `("[clef: " @Ident "]")?`
	Key           string `("[key: " @Ident "]")?`
	Transposition int    `("[transpose: " @Num "]")?`
}

var (
	myLexer = lexer.Must(lexer.Regexp(`
		(?P<Ident>[a-zA-Z][a-zA-Z0-9 ]*)
		(?P<Num>\-?\d*)
		| (?P<Comment>#.*(\r\n|\n))
	`))

	parser = participle.MustBuild(&PlainMusic{},
		participle.Lexer(myLexer),
		participle.Elide("Comment"),
	)
)

func main() {
	pm := &PlainMusic{}
	file, err := os.Open("mary had a little lamb.txt")
	defer file.Close()
	if err != nil {
		log.Fatal(err)
	}

	err = parser.Parse(file, pm)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(pm)
}
```

and when i run i get this error:
`15:29:05 mary had a little lamb.txt:1:1: invalid token '['`

what am i missing to make this work

**Comment by Strosel** [comment]
After further inspection it seems like it just reacts to anything in position 1:1 in the file as invalid.

**Comment by alecthomas** [comment]
There are a couple of problems here.

1. Your lexer doesn't produce `[` as a token, but you're asking the parser to match it.
2. Once your lexer produces punctuation as a token type, you should modify your parse grammar to match each one individually rather than combining them. eg.

```go
type Instrument struct {
	Name          string `("[" "instrument" ":" @Ident "]")?`
	Clef          string   `("[" "clef" ":" @Ident "]")?`
	Key           string `("[" "key" ":" @Ident "]")?`
	Transposition int    `("[" "transpose" ":" @Num "]")?`  
}
```
