### ISSUE TITLE
Any examples or recommendations for using participle with CEL? 

### ISSUE THREAD

**Issue by c4milo** [alecthomas/participle#55]
https://godoc.org/github.com/google/cel-go/cel

BTW, participle has been a joy to use, thank you!

**Comment by alecthomas** [comment]
You're welcome!

What did you have in mind? It looks like CEL has its own parser already?

**Comment by c4milo** [comment]
I didn’t want to reinvent the expression language for my little configuration language. I was thinking to parse expressions as strings first and then parse them and evaluate them with CEL. Does that make sense?

**Comment by c4milo** [comment]
This was not a good idea, I went for defining my own expression language using participle instead. Thanks!
