### ISSUE TITLE
Incorrect type when marshaling slice

### ISSUE THREAD

**Issue by sleepinggenius2** [alecthomas/participle#58]
First off, thank you for a great library!

I ran into a small issue trying to marshal into a slice field with a type alias.

```go
type Identifier string

type Foo struct {
	Identifiers []Identifier `parser:"@Ident+"`
}
```
`panic: reflect.Set: value of type string is not assignable to type foo.Identifier`

It looks like the code checks that the kind is the same, but does not check the type:

https://github.com/alecthomas/participle/blob/55fa45137c779173e288dc30eb8b595130f8d679/nodes.go#L403-L406

I was able to make the following change and it seems to work as expected now:

```go
if v.Kind() == t.Kind() {
	if v.Type() != t {
		v = v.Convert(t)
	}
	out = append(out, v)
	continue
}
```

**Comment by alecthomas** [comment]
Thanks, but it would be great if you could send a PR?

**Comment by sleepinggenius2** [comment]
PR submitted
