### ISSUE TITLE
Panic on empty disjunction node

### ISSUE THREAD

**Issue by sleepinggenius2** [alecthomas/participle#60]
I came across this one today.

When there is an empty node in a disjunction, it adds `nil` to the nodes slice, which causes the following panic because `a == nil` in the code below:
`panic: runtime error: invalid memory address or nil pointer dereference`

https://github.com/alecthomas/participle/blob/ed80074ea4ccfd35a6a7d8afd487ad0318faf6b8/nodes.go#L195

Example:
```go
type Foo struct {
	Field string `parser:"@( \"foo\" | | \"bar\" | \"baz\" )"`
}
```

I'm not sure if you would want that syntax to generate a build error or for the `nil` node to be ignored at runtime.  I'd be happy to submit a PR for either option.

**Comment by alecthomas** [comment]
That should definitely be an error. A PR would be appreciated, thanks.

**Comment by sleepinggenius2** [comment]
PR submitted
