### ISSUE TITLE
Error parsing into slice of Parseable

### ISSUE THREAD

**Issue by sleepinggenius2** [alecthomas/participle#62]
I've run into an issue trying to parse into a slice of Parseable.

In the code below, the checks are against `rt`, but if you change them to `t`, then it works as expected.  I have tested this with a Parseable string type and a Parseable struct type, as well as running the full test suite, and everything passes.  Given the explicit `rt := t` line though, I figured there might be some history to check with you on before submitting a PR.

https://github.com/alecthomas/participle/blob/ed80074ea4ccfd35a6a7d8afd487ad0318faf6b8/grammar.go#L26-L37

## Test Code
```go
package main

import (
	"fmt"
	"strconv"

	"github.com/alecthomas/participle"
	"github.com/alecthomas/participle/lexer"
)

type Bar struct {
	A int
}

func (x *Bar) Parse(lex lexer.PeekingLexer) error {
	token, err := lex.Next()
	if err != nil {
		return err
	}
	x.A, err = strconv.Atoi(token.Value)
	return err
}

type Foo struct {
	Bars []Bar `parser:"@@+"`
}

func main() {
	foo := &Foo{}
	parser := participle.MustBuild(foo)

	err := parser.ParseString("1 2 3", foo)
	fmt.Printf("Got error=%v value=%+v", err, foo)
}
```

### Expected
`Got error=<nil> value=&{Bars:[{A:1} {A:2} {A:3}]}`

### Actual
`panic: Bars: can not parse into empty struct main.Bar`

**Comment by alecthomas** [comment]
Thanks for the report, I'll take a look today.

**Comment by alecthomas** [comment]
I think the original intent of that code was to dereference pointers, but it appears to work without it so I'm not sure what happened. Anyway, I applied your suggestion and it seems to work. Thanks!
