### ISSUE TITLE
why not "==" works?

### ISSUE THREAD

**Issue by luochen1990** [alecthomas/participle#64]
I'm trying to parse comparison node as following:

```
type pCmp struct {
	Left *pSum		`@@`
	Op string		`( @("==" | "!=" | ">=" | ">" | "<=" | "<" )`
	Right *pSum		`  @@ )?`
}
```

And find it failed to parse `"1 == 2"`.  So I searched this similar thing in the examples and find the [example of expr2](https://github.com/alecthomas/participle/blob/master/_examples/expr2/main.go) has similar thing, but implemented by a different way:

```
type Comparison struct {
	Addition *Addition   `@@`
	Op       string      `[ @( ">" | ">" "=" | "<" | "<" "=" )`
	Next     *Comparison `  @@ ]`
}
```

So I change my code into this style, from things like `"=="` into `"=" "="`, and now it works for `"1 == 2"`, but it also parse `"1 =  = 2"` successfully, which is unexpected.

So, if `"=="` is invalid, then how should I write a parser which accept `"1 == 2"` but reject `"1 =  = 2"`?

**Comment by alecthomas** [comment]
This is due to the lexer. If your lexer emits separate `=` and `==` tokens then your parser can use them.

**Comment by alecthomas** [comment]
To clarify, the default lexer doesn't emit separate tokens for the composite operators, so the use in expr2 is a bit of a hack. Ideally expr2 would have its own lexer.
