### ISSUE TITLE
How to debug when the parser doesn't work as expected?

### ISSUE THREAD

**Issue by luochen1990** [alecthomas/participle#65]
Is there some debugging mechanism provided by this package which we can use to inspect current token and current matching struct when failed to parse?

**Comment by alecthomas** [comment]
Alas no, there is no such functionality. I think this would be relatively straightforward to add, as the `parseContext` contains the currently targeted struct and token cursor.

**Comment by alecthomas** [comment]
Ah, I forgot that there is something: you will get a partial AST returned with your error. So the "deepest" node in the AST will be the last matching entry.

**Comment by luochen1990** [comment]
@alecthomas Thanks, that is very helpful 👍
