### ISSUE TITLE
Use of regex in EBNF

### ISSUE THREAD

**Issue by stevefan1999-personal** [alecthomas/participle#68]
I wonder if we could use regex to define the range of a terminal? For example I want to use Unicode category L instead of ASCII alphanums to denote identifiers. As of now I cannot mix regexp and EBNF grammar lexer at once.

**Comment by alecthomas** [comment]
I don't think it makes sense to support arbitrary regex in the EBNF lexer. At that point why not use the Regex lexer?

It sounds like it would be sufficient to support Unicode escape sequences?

**Comment by stevefan1999-personal** [comment]
@alecthomas A more compromised move is to allow the composition of lexers, so we can mix-n-match some EBNF and Regexp altogether and thoroughly, that would make much more sense to me.

The general syntax of denoting terminals in regexp is very unfavorably ugly, and it doesn't like missed brackets. It would be much cooler to see and use the "GNU flex" approach here.

**Comment by alecthomas** [comment]
What's an example of where this capability would be useful?

**Comment by stevefan1999-personal** [comment]
I was having this kind of code to trying to overcome the restriction of not be able to use regex in EBNF

```golang
var (
	grammarLexer = lexer.Must(ebnf.New(`
      RecordType = "CNAME" | "A" [ "AAA" ] | "MX" | "NS" | "SRV" | "TXT" .
      AssignOp = "->" | "=" [ ">" ] | "to" .
      Whitespace = " " | "\t" | "\n" | "\r" .
      Colon = ":" .
      Term = ";" | "," .
      Bracket = "{" | "}" | "(" | ")".
      Quotes = "'" | "\"" .
    `))
	parser = checkError(
		participle.Build(
			&struct {
				Rules []RuleSection `@@*`
			}{},
			participle.Lexer(lexer.Must(lexer.Regexp(`(?P<Identifier>[_.0-9]([_.0-9]|\p{L})*)`))),
			participle.Lexer(grammarLexer),
			participle.Elide("Whitespace", "Term"),
			participle.CaseInsensitive("RecordType"),
		),
	).(*participle.Parser)
)
```
However, this wouldn't work since the last lexer option overrides the former one, making the token not found and such failure to parse.

**Comment by alecthomas** [comment]
I feel like that specific example is solvable in a clean way just by extending the EBNF lexer to support unicode categories.

Do you have any other situations in mind where the ability to combine lexers would be useful?

**Comment by alecthomas** [comment]
Also see #25, though the intent is slightly different.

**Comment by alecthomas** [comment]
BTW the lexer is an interface, so if you want to write your own with the appropriate semantics it's fairly straightforward.

**Comment by alecthomas** [comment]
In hindsight I think what you're asking for is a simpler regex-based lexer syntax, is that correct? 

eg.

```
RecordType = CNAME|A|AAAA|MX|NS|SRV|TXT
AssignOp = ->|=[>]?|to
Whitespace = [ \t\n\r]
Colon = :
Term = ;,
 Bracket = [{}()]
 Quotes = "|\"
```
