### ISSUE TITLE
Can we exclude a particular string or character while parsing a statement?

### ISSUE THREAD

**Issue by HaroonRaizada** [alecthomas/participle#69]
Like have *->including everything
! is for non-empty.

similarly is there any thing to avoid a particular string?

type struct abc{
tab string `@"BACK"`
}

here in above code we want to exclude BACK keyword.

**Comment by Sylvain303** [comment]
Hi,

Could you put the example you want to parse?

It seems you could achieve this at lexer level, discarding some token. So they are not given to the parser, and not part of the grammar. The comment are often processed that way.

INI example parser use that method: 

https://github.com/alecthomas/participle/blob/master/_examples/ini/main.go

Hope that helps,
Sylvain.

**Comment by alecthomas** [comment]
As @Sylvain303 mentions, I think what you're asking for should be done in the lexer, by NOT matching the words you want to exclude. If you have a more specific example there might be a more concrete answer.
