### ISSUE TITLE
Parsing comments in file (eg. // or /* */ ) is not supported

### ISSUE THREAD

**Issue by murdockq** [alecthomas/participle#7]
I have found a problem while trying to parse the comments out of a thrift file into the AST and it does not appear to be possible with the current implementation.

I traced it down to the default lexer using the scanner.Mode = SkipComments.  Is it possible to set the Mode to use ScanComments and then make a test that allows using the @Comment type.

Here is the snippet I was trying to use for my tests
```
/* comment test */
// testing a comment
enum TweetType {
    TWEET
    RETWEET = 2
    DM = 3
    REPLY
}
```

```
type Comment struct {
	Message string `@Comment`
}

type Thrift struct {
	Includes   []string     `{ "include" @String`
	Comments   []*Comment   `  | @@`
	Namespaces []*Namespace `  | @@`
	Structs    []*Struct    `  | @@`
	Exceptions []*Exception `  | @@`
	Services   []*Service   `  | @@`
	Enums      []*Enum      `  | @@`
	Typedefs   []*Typedef   `  | @@`
	Consts     []*Const     `  | @@ }`
}
```

My eventual goal is to make sure the comments carry over when running code generation into the native language output.

**Comment by alecthomas** [comment]
We have two options: send a PR adding a new constructor allowing a scanner to be passed int, or write your own scanner. I'd be happy to accept a PR for the former.

**Comment by murdockq** [comment]
Closing since you can now specify your own parser. Thank you.
