### ISSUE TITLE
Question about syntax

### ISSUE THREAD

**Issue by akupila** [alecthomas/participle#72]
Hey @alecthomas

Thanks for putting this package together!

I'm trying to write a parser to parse something similar to object access in javascript (`foo.bar[2]`) but i keep running into `unexpected token "["`.

Here's what i'm trying to do:

```go
package main

import (
	"log"

	"github.com/alecthomas/participle"
)

type pathLiteral struct {
	Parts []part `@@ { "." @@ }`
}

type part struct {
	Name  *string `@Ident`
	Index *index  `| "[" @@ "]"`
}

type index struct {
	Name  *string `@Ident`
	Index *int64  `| @Int`
}

func main() {
	input := "abc.def[3].ghi"

	parser := participle.MustBuild(&pathLiteral{})

	var lit pathLiteral
	if err := parser.ParseString(input, &lit); err != nil {
		log.Fatal(err) // 2019/09/19 17:49:26 <source>:1:8: unexpected token "["
	}
}
```

I would expect this to work but for some reason it doesn't recognize the `[`. Could you please nudge me in the right direction? I'm completely new to `ebnf` and quite new to parsers in general.

Thank you

**Comment by alecthomas** [comment]
I think your problem is that you have `@Ident | "[" @@ "]"`, which means `@Ident OR [...]`. What you want is `@Ident ("[" @@ "]")?` (note the `?` which means the previous element is optional. Let me know if that works.

**Comment by akupila** [comment]
Yes, that works. Thank you!

```go
type part struct {
	Name  *string `@Ident`
	Index *index  `("[" @@ "]")?`
}
```

But why does it work? I understood `|` as "match Name _or_ Index". I tried to use the `|` based on the hcl example: https://github.com/alecthomas/participle/blob/b7d3966edc426f708308548cc8b2fbcbf3f2adeb/_examples/hcl/main.go#L19-L25

**Comment by alecthomas** [comment]
The input this is matching is `bar[2]`, so if you have `@Ident | "[" ...` this will match the input token `bar` to `@Ident`, then terminate the `|` expression. At this point the parser will be back in `pathLiteral` expected a `.` or EOF, but encounters a `|`.

**Comment by alecthomas** [comment]
The example from HCL is different in that it is "match one of these inputs". Your expression is "match an identifier, optionally followed by an index".

**Comment by akupila** [comment]
Thanks for the clarification, that makes sense.

However, this doesn't do what i want after all. I want to match either `Name` or `Index` but not both (like in the hcl example). The expected tokens would be:
```
abc
def
3
ghi
```

**Comment by akupila** [comment]
I think i figured it out, thanks for the help!

Here's the code in case somebody else runs into a similar problem:

```go
package main

import (
	"log"

	"github.com/alecthomas/participle"
	"github.com/kr/pretty"
)

type pathLiteral struct {
	Parts []part `@@ { "."? @@ }`
}

type part struct {
	Name  *string `@Ident`
	Index *index  `| "[" @@ "]"`
}

type index struct {
	Name  *string `@Ident`
	Index *int64  `| @Int`
}

func main() {
	input := `abc.def[3][4].ghi`

	parser := participle.MustBuild(&pathLiteral{})

	var lit pathLiteral
	if err := parser.ParseString(input, &lit); err != nil {
		log.Fatal(err) // 2019/09/19 17:49:26 <source>:1:8: unexpected token "["
	}

	pretty.Println(lit)
}
```
Output:
```
main.pathLiteral{
    Parts: {
        {
            Name:  &"abc",
            Index: (*main.index)(nil),
        },
        {
            Name:  &"def",
            Index: (*main.index)(nil),
        },
        {
            Name:  (*string)(nil),
            Index: &main.index{
                Name:  (*string)(nil),
                Index: &int64(3),
            },
        },
        {
            Name:  (*string)(nil),
            Index: &main.index{
                Name:  (*string)(nil),
                Index: &int64(4),
            },
        },
        {
            Name:  &"ghi",
            Index: (*main.index)(nil),
        },
    },
}
```

**Comment by alecthomas** [comment]
Unless you're doing something quite unusual, that's probably not correct for a couple of reasons.

1. That will now also match `foo bar` now that `.` is optional.
2. The associativity of subscripts is usually quite high, which your grammar does not capture. For example `foo.bar[10]` should have this associativity `(foo.(bar[10]))` not `(foo.bar)[10]`.

The example I gave is the correct way to structure the AST for a subscript operator.

**Comment by akupila** [comment]
Oh, thanks for the update. I'll need to investigate a bit further. I also realized myself that `abc.[1]` would not return an error, when it should.

Anyway, i think i have a better understanding of how this works now. Thanks again for the help
