### ISSUE TITLE
Wrap errors returned from setField in lexer.Error

### ISSUE THREAD

**Issue by pnehrer** [alecthomas/participle#74]
Errors that are returned from `setField` (e.g., due to value conversion) lose positional information as they are not `lexer.Error`s.

Even thought the error message itself is decorated here: https://github.com/alecthomas/participle/blob/master/nodes.go#L470, it would be great if the full lexer.Error could be returned instead (or another error type that carries Position) so that we can extract the exact token position.

**Comment by alecthomas** [comment]
Coincidentally I was just discussing this recently in another ticket. Good idea.

**Comment by alecthomas** [comment]
Let me know how that works.
