### ISSUE TITLE
struct field tag from tutorial causing error?

### ISSUE THREAD

**Issue by beattymg** [alecthomas/participle#77]
Hi I tried running the tutorial in a local go file, but I get the following errors for each struct tag from the grammar trying to run it:

```
example.go:4:2: struct field tag `@@*` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair
example.go:5:2: struct field tag `@@*` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair
example.go:9:2: struct field tag `"[" @Ident "]"` not compatible with reflect.StructTag.Get: bad syntax for struct tag key
example.go:10:2: struct field tag `@@*` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair
example.go:14:2: struct field tag `@Ident "="` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair
example.go:15:2: struct field tag `@@` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair
example.go:19:2: struct field tag `  @String` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair
example.go:20:2: struct field tag `| @Float` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair
```

It also fails in a go playground: https://play.golang.org/p/UGg5M3qPqVX. Any idea what I could be missing here?

**Comment by alecthomas** [comment]
You can use the `parser:"..."` tag.

I'm surprised you get those errors locally when running `go run`. I cannot replicate that. They are `go vet` errors, which shouldn't normally prevent compilation.

**Comment by stevegt** [comment]
For future travelers who run into errors similar to these when running `go vet` on participle or its examples:
```
struct literal uses unkeyed fields
bad syntax for struct tag pair
```

Disabling these checks will silence the errors:
```
go vet -structtag=false -composites=false
```

I tend to run `go vet` automatically as part of my workflow and don't like disabling checks, but at this time I'm not asking Alec if we should change the code to get rid of those `go vet` errors.  Updating participle's coding style to make it more compatible with modern Go versions would be great, but:

- Adding the field and struct tags keys in the participle code base would mean touching around 900 lines of existing code.  
- While altering those 900 lines could be automated, it would be a design decision that would make participle's code and examples less readable.

*Maybe* this would make sense for a hypothetical participle v3.

**Comment by laktak** [comment]
Thanks @stevegt 

For [coc-go](https://github.com/josa42/coc-go) it's:

```
{
  "go.goplsOptions": {
    "analyses": {
      "structtag": false,
      "composites": false
    }
  }
}
```

**Comment by Sermuns** [comment]
For reference, this works for `lspconfig` neovim:

```lua
require('lspconfig').gopls.setup {
  settings = {
    gopls = {
      analyses = {
        structtag = false,
      },
    },
  },
}
```
