### ISSUE TITLE
Generating text representation from grammar struct

### ISSUE THREAD

**Issue by Gilgames000** [alecthomas/participle#78]
Is there a way to generate the textual representation from the annotated grammar struct? For example, I would like to parse a string then edit the value of some fields then put it back into text form.  Alternatively, create a struct and initialize it with custom values then converting it to a string by using the grammar embedded in the struct type. I know I could write a "serializer" of some sort, I'm just curious if there's a way to do it by leveraging the existing code. Thanks!

**Comment by alecthomas** [comment]
I usually just add String() methods to my grammar, mainly because (usually) a great deal of information is missing from it, like white space, comments, etc.

**Comment by Gilgames000** [comment]
That would actually suit my needs. Didn't think about it, thanks!
