### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ravenpride** [alecthomas/participle#79]
Hello,

first of all: Thank you for this great piece of work!

It really helped me to parse a custom configuration file. Everything I need now is an explicit license I could refer to when writing the Third-Party-Notices file for my project. Could you please add a license file for your project, please?

Thank you in advance!

Sascha

**Comment by alecthomas** [comment]
You're welcome. License is in https://github.com/alecthomas/participle/blob/master/COPYING
