### ISSUE TITLE
TOML parser example eBNF does not handle floats

### ISSUE THREAD

**Issue by tmalaher** [alecthomas/participle#81]
Using the example TOML parser from the README.md:

```go
toml := &TOML{}
err := tomlParser.ParseString(`
    int=1
    string="a string"
    float=3.4
`, toml)
```

I get: `4:10: unexpected token ".4"`

It seems the eBNF for `Int` is capturing the "3", leaving the ".4" as unparsable.

I had a similar problem in an eBNF grammar I was creating. I solved it by using regexps, but I'd prefer to use eBNF if possible.

What's the fix to this situation?

**Comment by alecthomas** [comment]
Switching to the new regex lexer would be a way.

**Comment by alecthomas** [comment]
There is EBNF out there for floats, but it will also match integers, so you'd need a lexer wrapper to check if the constant is a float or not, or just use float always.

**Comment by alecthomas** [comment]
The EBNF lexer is being removed in the v1 branch.
