### ISSUE TITLE
Empty single quoted string and empty double quoted string

### ISSUE THREAD

**Issue by blue-bird1** [alecthomas/participle#82]
I try use  `@string` parse Matches an  string, but I found that an empty single quoted string will cause my matching error. Everything else works, Why do empty single quotes match errors?

```
type Value struct {
	String *string  `@String`
	FunctionCall string `|@Ident"("")"`
	Number *float64 `|@Float`
	Int    *int     `|@Int`
	Ident  string   `|@Ident`
}
```

**Comment by alecthomas** [comment]
This is due to poor judgement on my part. I modified the output tokens of the Go lexer to allow single quoted strings, while still supporting single characters. I shouldn't have done that, so unfortunately there's no real fix for this.

I would suggest using a custom lexer.

Additionally, I think I will revert that behaviour because it's so fragile.

**Comment by blue-bird1** [comment]
hi I'm trying to write a parser now, but I'm having a problem. 

```go
var signParser = lexer.Must(regex.New(`
Name = [\w+\\]*\w+
`)

type NameTest struct {
		Name string `@Name`
}

nameParser :=  participle.MustBuild(&NameTest{},participle.Lexer(signParser))


name := &NameTest{}

err = nameParser.ParseString("test\\test", name)
```

I can only match to` \ test` . And I tried this expression at `https: // regex101.com /`, but it succeeded. What did I miss?

**Comment by alecthomas** [comment]
Your example works fine for me on latest master.

```
package main

import (
	"github.com/alecthomas/repr"

	"github.com/alecthomas/participle"
	"github.com/alecthomas/participle/lexer"
	"github.com/alecthomas/participle/lexer/regex"
)

func main() {
	var signParser = lexer.Must(regex.New(`
Name = [\w+\\]*\w+
`))

	type NameTest struct {
		Name string `@Name`
	}

	nameParser := participle.MustBuild(&NameTest{}, participle.Lexer(signParser))

	name := &NameTest{}

	err := nameParser.ParseString("test\\test", name)
	if err != nil {
		panic(err)
	}
	repr.Println(name)
}
```

**Comment by blue-bird1** [comment]
Since I didn't expect other parser parts to have an impact, I ignored some. I tested and found
```
var signParser = lexer.Must(regex.New(`
alpha = [a-z|A-Z] 
String = ["'"|"\""]([\w|\\]*)["'"|"\""] 
Name = [\w+\\]*\w+
`))
```

To reproduce

**Comment by alecthomas** [comment]
"alpha" matches the input first

**Comment by blue-bird1** [comment]
Sorry, I confused the implementation principle.
