### ISSUE TITLE
Can't parse string with integers and dots

### ISSUE THREAD

**Issue by Gilgames000** [alecthomas/participle#87]
I'm having trouble parsing a string like `1.2.3` (minimal example [here](https://play.golang.org/p/jPpX_SycBfh)). It works just fine, though, if I try to parse `1-2-3`  ([here](https://play.golang.org/p/iitKQv41ZWa)) or `a.b.c` ([here](https://play.golang.org/p/C0nY_g1Blh-)). I can't seem to wrap my head around why the parsing is failing with integers and dots. Any thoughts or better ways to parse such a string (aside from using a custom lexer)? Thanks!

**Comment by alecthomas** [comment]
This is caused by the default lexer differentiating between float and int tokens. It's returning "1.2" as a float token. If you don't want that you'll need to define your own lexer.
