### ISSUE TITLE
Case insensitive literals

### ISSUE THREAD

**Issue by dspasibenko** [alecthomas/participle#9]
It wold be nice if literals could be matched case-insensitive. For now if I write

```
OrCondition struct {
	And []*Condition `@@ { "AND" @@ }`
}
```
the literal `AND` is matched with uppercase word `AND` only, but not `and`, which will be not matched.

**Comment by alecthomas** [comment]
You're in luck! This can be achieved at the lexer level with the [Upper](https://godoc.org/github.com/alecthomas/participle/lexer#Upper) lexer interceptor. You can see an example of it in use in the [SQL lexer](https://github.com/alecthomas/participle/blob/master/_examples/sql/main.go).
