### ISSUE TITLE
Help with parsing a MongoDB Cli command

### ISSUE THREAD

**Issue by sanket28** [alecthomas/participle#90]
Hello,

Thanks for an awesome library! I'm super new to this so please bear with me. I'm trying to parse a mongo cli command and I have the following code:

```
package mongodb

import (
	"fmt"
	"testing"

	"github.com/alecthomas/participle"
)

type MongoCommand struct {
	DB             string     `@Ident`
	CollectionName string     `"." @Ident`
	Operation      *Operation `@@`
}

type Operation struct {
	Op   string                 `"." @Ident`
	Data string `"(" @Ident ")"`
}

func Test_ParseCommand(t *testing.T) {
	parser, err := participle.Build(&MongoCommand{})
	ast := &MongoCommand{}
	err = parser.ParseString(`db.myAwesomeCollection.insert({"cool.name": 1})`, ast)
	if err != nil {
		t.Fatal(err)
	}
	fmt.Printf("AST %+v and operation %+v\n", ast, ast.Operation)
}
```

But I always get the error `unexpected "{" (expected <ident> ...)` 

If I remove the Data member from the `Operation` struct I get the DB name, CollectionName and Op just fine. 

Basically what I want to achieve is get everything inside the `(` `)` braces as a string.

Please advise. Thanks

**Comment by alecthomas** [comment]
Alas, that is not possible. In Participle, parsing is broken down into two phases: lexing, then parsing. Lexing produces tokens (fragments of text) without any knowledge of the structure of the language being parsed. In your example, the tokens would be `['{', '"cool.name", '}']`.

You'll basically need an expression parser here. There are a couple of examples in the _examples directory, but they'll need to be extended to support Mongo's particular expression syntax, including what looks like map literals.

BTW there's a Slack channel for general discussion.
