### ISSUE TITLE
help on parse "anything between two words"

### ISSUE THREAD

**Issue by kaixinbuyu** [alecthomas/participle#92]
I'm trying to parse,extract,replace table names in SQL script,
(only interested on tables in FROM clause,extract tables and replace back to the SQL script)
others clause like select clause,where clause should keep the same( in order to support on all databases, mysql,mssql,oracle,...):

```go
type Select struct {

	Select string `SELECT @KeepScript`    //  <- 2. keep everything from SELECT until FROM

	From *FromClause `[ FROM @@ ]`   // <- 1.parse tables here,maybe nested.

	Where string `[ WHERE @KeepScript ]`   // <- 3.keep everything like where,order by,group...
	GroupBy string `[ GROUPBY @KeepScript ]`
	OrderBy string `[ ORDERBY @KeepScript ]`
	Limit int `[ LIMIT @Number ]`
	End string `[ @";" ]`
}
```

I tryied a lot to find a way catch @@KeepScript  but all failed.
How to impl KeepScript struct here by participle?
Is participle support "locate"/search and parse in a part of strings?

**Comment by alecthomas** [comment]
This is possible, but kind of involved. Basically you'll need a custom tokeniser with `FROM`, `WHERE`, etc. as higher priority tokens than _everything_ else, then you'll need to match on the keywords followed by matching on anything BUT a keyword.

**Comment by kaixinbuyu** [comment]
Thanks for your suggestion,I'll try to impl a custom lexer.
