### ISSUE TITLE
Prevent scanner.Int from interpretting 0 padded Int's as octal

### ISSUE THREAD

**Issue by umeat** [alecthomas/participle#94]
Is it possible to prevent scanner.Int from interpreting integers which are padded with a 0 on the left as octal?

My type:

```
type Epoch struct {
     Year int `@Int`
     Month int `@Int`
     Day int `@Int`
     Hour int `@Int`
     Minute int `@Int`
     Second float64 `@Float`
     EpochFlag int `@Int`
     NumSatellites int `@Int`
     ClockOffset float64 `@("-"? Float)?`
}
```

Example data:

```
> 2018 11 24 00 07  0.0000000  0 55
> 2018 11 24 00 07 30.0000000  0 55
> 2018 11 24 00 08  0.0000000  0 55
```

Of course as soon as you get to 08, Parse errors with: `invalid digit '8' in octal literal`

**Comment by alecthomas** [comment]
There's no way to directly alter the scanner, but a token mapper should be able to fix this for you. Something like:

```go
participle.MustBuild(&Epoch{}, participle.Map(func(t lexer.Token) (lexer.Token, error) {
  t.Value = strings.TrimPrefix(t.Value, "0")
  return t, nil
}, "Int"))
```

**Comment by alecthomas** [comment]
(in reality you'll probably need to be a bit smarter about this  to avoid `00` turning into an empty string, and probably other corner cases)
