### ISSUE TITLE
parse struct only from one line

### ISSUE THREAD

**Issue by RileyJia** [alecthomas/participle#97]
I am trying to parse a file looks like this:
```
//section 1
object1.1, // description for 1.1
object1.2, // description for 1.2
object1.3, 
// section 2
object2.1, 
object2.2 // description for 2.2
```

And I want it to parse to a new file look like this
```
{
  "objectList": [
    {
      "name": "object1.1",
      "description": "description for 1.1"
    },{
      "name": "object1.2",
      "description": "description for 1.2"
    },{
      "name": "object1.3",
      "description": ""
    },{
      "name": "object2.1",
      "description": "description for 2.1"
    },
...
]
}
```

The lexer and parser struct I got right now:
```
var tsLexer = lexer.Must(lexer.Regexp(
	`(?m)` +
		`(\s+)` +
		`|(?P<Ident>[a-zA-Z][a-zA-Z_\d]*)` +
		`|(?P<Comment>\/\/[^\n]+)` +
		`|(?P<Punct>[][,])`,
))

type Property struct {
	Comment *string `(@Comment`
	Key     string  `| @Ident`
	Desc    string  `(",")? (@Comment)?)`
}
```

However, for object 1.3, it will get the description "section 2". I am wondering is there a way I can restrict the struct parsing only in one line, so object 1.3 wouldn't get description from the next line.
Thanks.

**Comment by alecthomas** [comment]
Yes this is possible but you'll need to promote `\n` to a first class token and explicitly match on it.

**Comment by RileyJia** [comment]
thanks for the quick reply, but could you be more specific? I am not sure how I can do the first class token part.

**Comment by alecthomas** [comment]
You'll need to do something  like `(?P<NL>\n)` in your lexer, then explicitly match against that in your parser struct.

**Comment by alecthomas** [comment]
Note that it will need to precede `\s` to take effect.
