### ISSUE TITLE
Misunderstanding of alternatives in structs?

### ISSUE THREAD

**Issue by aod** [alecthomas/participle#98]
I cannot get the alternative `|` to work in my rudimentary parser... I'm banging my head against the wall here don't know what to do. Is there something I'm not fully grasping within the program below?

```go
type Grammar struct {
	Pos lexer.Position

	DateRange *DateRange `@@`
}

type DateRange struct {
	SingleYear *string `  @Year`
	AllYears   *string `| ":"`
	FinalYear  *string `| ":" @Year`
	StartYear  *string `| @Year ":"`
	FullRange  *string `| @(Year ":" Year)`
}
```

https://play.golang.org/p/obbeJyVdmiF

For example if I want to parse `:2015` in the playground link above it reports the following:

```
<year> | ":" | ":" <year> | <year> ":" | <year> ":" <year>: 1:1: invalid token ':'
```

or with `2015:`

```
<year> | ":" | ":" <year> | <year> ":" | <year> ":" <year>: 1:5: invalid token ':'
```

**Comment by alecthomas** [comment]
The fixed version is [here](https://play.golang.org/p/srJPSxfbzzX). There were a few problems: 

1. If you have `":"` but also want to be able to match `":" @Year`, order is important, as the former will always successfully match first.
2. You must increase the lookahead using `participle.UseLookahead(3)` if you want to backtrack when a branch fails.
3. The branch `":"` would never capture anything.

That said, I would probably change your grammar to something more like [this](https://play.golang.org/p/EkmjOINRygB):

```go
type Grammar struct {
	Pos lexer.Position

	DateRange *DateRange `parser:"@@"`
}

type DateRange struct {
	Start string `parser:"@Year?"`
	End   string `parser:"':' @Year?"`
}
```

**Comment by alecthomas** [comment]
Hope that helps, all the best.
