### ISSUE TITLE
Signal: Killed when parsing string surrounded by parentheses

### ISSUE THREAD

**Issue by jcklie** [alecthomas/participle#99]
I just tried out your project for parsing LDAP search filters. I got started pretty quickly, but then I stumbled over a really strange problem. When I run the following, I get a "Signal: killed". When I change `s := "(foo=bar"` to `s := "(oo=bar"` then it throws the expected parse error. What am I doing wrong? I looked at the parser examples and they also parse values surrounded by parens.

```
package main

import "fmt"
import "github.com/alecthomas/participle"
import "github.com/alecthomas/participle/lexer"
import "github.com/alecthomas/participle/lexer/ebnf"

type Filter struct {
    Value *Simple `"(" @@ ")"`
}

type Simple struct {
    Attr string `@LdapString`
    FilterType string `@FilterType`
    Value string `@LdapString`
}

func main() {
    fmt.Println("hello world")
    var lexer = lexer.Must(ebnf.New(`
        FilterType = ( "=" | "~=" | ">=" | "<=" ) . 
		LdapString = { "a"…"z" } . 
	`))

    var parser = participle.MustBuild(
        &Filter{},
		participle.Lexer(lexer),
    )

    fmt.Println("Parser built")
    fmt.Println(parser)

    s := "(foo=bar"
    filterList := &Filter{}
    err := parser.ParseString(s, filterList)

    fmt.Println("Parsed")
    fmt.Println(filterList)
    fmt.Println(err)
}
```

> go version go1.14.5 linux/amd64
> participle 0.5.0

**Comment by alecthomas** [comment]
If you receive a signal in Go, it's always either an internal Go runtime error, a compiler error, or a hardware error on your machine. I would try Go 1.13 and see if that fixes the signal.

**Comment by jcklie** [comment]
Thank you for the reply. I tried also a totally different machine with `go version go1.12.7 linux/amd64` and the same happens. It gets killed because it runs out of memory. I think that is either a problem with my grammar or the code. Were you able to reproduce it?

**Comment by alecthomas** [comment]
Ah interesting, thanks for the additional info. I'll take a look.

**Comment by alecthomas** [comment]
Looks like a bug in the EBNF lexer. If you swap the lexer out for the regex one, it will not crash:

```go
	var lexer = lexer.Must(regex.New(`
		FilterType = =|~=|>=|<=
		LdapString = [a-z]
	`))

```

**Comment by alecthomas** [comment]
Ok so this EBNF lexer definition works:

```go
	var lexer = lexer.Must(ebnf.New(`
	    FilterType = "=" | "~=" | ">=" | "<=" .
		LdapString = letter { letter } .
		Punct = "(" | ")" .
		letter = "a"…"z" .
	`))

```

The problem with your original lexer is that `{ "a"…"z" }` matches _zero_ or more, so it always matches zero, and results in an infinte loop. The lexer should check for this though, and error.

**Comment by jcklie** [comment]
Thank you! I will use the regex lexer from now on, I just did not do it at first because I did not find documentation for it.

**Comment by alecthomas** [comment]
Okay fixed. This will now error with:

```
rule "LdapString" matched, but did not consume any input
```

Thanks for the bug report!
